/*
 * generated by Xtext 2.37.0
 */
package projetIDM.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractJavaSFTValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(projetIDM.javaSFT.JavaSFTPackage.eINSTANCE);
		return result;
	}
}
