<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="table" nsURI="http://table" nsPrefix="table">
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnelement" upperBound="-1"
        eType="#//Column" containment="true" eOpposite="#//Column/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnid" lowerBound="1"
        eType="#//ColumnID" containment="true" eOpposite="#//ColumnID/table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fichierSource" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnID">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/columnid"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/columnelement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ColumnType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardColumn" eSuperTypes="#//Column"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedColumn" eSuperTypes="#//Column"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ColumnType">
    <eLiterals name="FLOAT"/>
    <eLiterals name="INT" value="1"/>
    <eLiterals name="BOOL" value="2"/>
  </eClassifiers>
</ecore:EPackage>
