/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import projetIDM.javaSFT.ClassName;
import projetIDM.javaSFT.Constant;
import projetIDM.javaSFT.ConstantAssignment;
import projetIDM.javaSFT.ConstantDeclaration;
import projetIDM.javaSFT.CosUnaire;
import projetIDM.javaSFT.CosUnaireList;
import projetIDM.javaSFT.CosUnaireNumber;
import projetIDM.javaSFT.DivisionBinaire;
import projetIDM.javaSFT.DivisionBinaireListList;
import projetIDM.javaSFT.DivisionBinaireListVal;
import projetIDM.javaSFT.DivisionBinaireValList;
import projetIDM.javaSFT.DivisionBinaireValVal;
import projetIDM.javaSFT.ExpUnaire;
import projetIDM.javaSFT.ExpUnaireList;
import projetIDM.javaSFT.ExpUnaireNumber;
import projetIDM.javaSFT.JavaSFT;
import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.MaxBinaire;
import projetIDM.javaSFT.MaxBinaireListList;
import projetIDM.javaSFT.MaxBinaireListVal;
import projetIDM.javaSFT.MaxBinaireValVal;
import projetIDM.javaSFT.MaxUnaire;
import projetIDM.javaSFT.Methode;
import projetIDM.javaSFT.MinBinaire;
import projetIDM.javaSFT.MinBinaireListList;
import projetIDM.javaSFT.MinBinaireListVal;
import projetIDM.javaSFT.MinBinaireValVal;
import projetIDM.javaSFT.MinUnaire;
import projetIDM.javaSFT.Operation;
import projetIDM.javaSFT.OperationBinaire;
import projetIDM.javaSFT.OperationUnaire;
import projetIDM.javaSFT.OppositeUnaire;
import projetIDM.javaSFT.OppositeUnaireList;
import projetIDM.javaSFT.OppositeUnaireNumber;
import projetIDM.javaSFT.Parameter;
import projetIDM.javaSFT.ProductBinaire;
import projetIDM.javaSFT.ProductBinaireListList;
import projetIDM.javaSFT.ProductBinaireListVal;
import projetIDM.javaSFT.ProductBinaireValVal;
import projetIDM.javaSFT.ProductUnaire;
import projetIDM.javaSFT.Return;
import projetIDM.javaSFT.SinUnaire;
import projetIDM.javaSFT.SinUnaireList;
import projetIDM.javaSFT.SinUnaireNumber;
import projetIDM.javaSFT.SqrtUnaire;
import projetIDM.javaSFT.SqrtUnaireList;
import projetIDM.javaSFT.SqrtUnaireNumber;
import projetIDM.javaSFT.SumBinaire;
import projetIDM.javaSFT.SumBinaireListList;
import projetIDM.javaSFT.SumBinaireListVal;
import projetIDM.javaSFT.SumBinaireValVal;
import projetIDM.javaSFT.SumUnaire;
import projetIDM.javaSFT.TypeList;
import projetIDM.javaSFT.TypeListNumber;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see projetIDM.javaSFT.JavaSFTPackage
 * @generated
 */
public class JavaSFTAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static JavaSFTPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JavaSFTAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = JavaSFTPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JavaSFTSwitch<Adapter> modelSwitch =
    new JavaSFTSwitch<Adapter>()
    {
      @Override
      public Adapter caseJavaSFT(JavaSFT object)
      {
        return createJavaSFTAdapter();
      }
      @Override
      public Adapter caseTypeList(TypeList object)
      {
        return createTypeListAdapter();
      }
      @Override
      public Adapter caseTypeListNumber(TypeListNumber object)
      {
        return createTypeListNumberAdapter();
      }
      @Override
      public Adapter caseClassName(ClassName object)
      {
        return createClassNameAdapter();
      }
      @Override
      public Adapter caseClass(projetIDM.javaSFT.Class object)
      {
        return createClassAdapter();
      }
      @Override
      public Adapter caseMethode(Methode object)
      {
        return createMethodeAdapter();
      }
      @Override
      public Adapter caseParameter(Parameter object)
      {
        return createParameterAdapter();
      }
      @Override
      public Adapter caseReturn(Return object)
      {
        return createReturnAdapter();
      }
      @Override
      public Adapter caseConstant(Constant object)
      {
        return createConstantAdapter();
      }
      @Override
      public Adapter caseConstantDeclaration(ConstantDeclaration object)
      {
        return createConstantDeclarationAdapter();
      }
      @Override
      public Adapter caseConstantAssignment(ConstantAssignment object)
      {
        return createConstantAssignmentAdapter();
      }
      @Override
      public Adapter caseOperation(Operation object)
      {
        return createOperationAdapter();
      }
      @Override
      public Adapter caseOperationUnaire(OperationUnaire object)
      {
        return createOperationUnaireAdapter();
      }
      @Override
      public Adapter caseOperationBinaire(OperationBinaire object)
      {
        return createOperationBinaireAdapter();
      }
      @Override
      public Adapter caseSumUnaire(SumUnaire object)
      {
        return createSumUnaireAdapter();
      }
      @Override
      public Adapter caseProductUnaire(ProductUnaire object)
      {
        return createProductUnaireAdapter();
      }
      @Override
      public Adapter caseMinUnaire(MinUnaire object)
      {
        return createMinUnaireAdapter();
      }
      @Override
      public Adapter caseMaxUnaire(MaxUnaire object)
      {
        return createMaxUnaireAdapter();
      }
      @Override
      public Adapter caseOppositeUnaire(OppositeUnaire object)
      {
        return createOppositeUnaireAdapter();
      }
      @Override
      public Adapter caseOppositeUnaireList(OppositeUnaireList object)
      {
        return createOppositeUnaireListAdapter();
      }
      @Override
      public Adapter caseOppositeUnaireNumber(OppositeUnaireNumber object)
      {
        return createOppositeUnaireNumberAdapter();
      }
      @Override
      public Adapter caseCosUnaire(CosUnaire object)
      {
        return createCosUnaireAdapter();
      }
      @Override
      public Adapter caseCosUnaireList(CosUnaireList object)
      {
        return createCosUnaireListAdapter();
      }
      @Override
      public Adapter caseCosUnaireNumber(CosUnaireNumber object)
      {
        return createCosUnaireNumberAdapter();
      }
      @Override
      public Adapter caseSinUnaire(SinUnaire object)
      {
        return createSinUnaireAdapter();
      }
      @Override
      public Adapter caseSinUnaireList(SinUnaireList object)
      {
        return createSinUnaireListAdapter();
      }
      @Override
      public Adapter caseSinUnaireNumber(SinUnaireNumber object)
      {
        return createSinUnaireNumberAdapter();
      }
      @Override
      public Adapter caseSqrtUnaire(SqrtUnaire object)
      {
        return createSqrtUnaireAdapter();
      }
      @Override
      public Adapter caseSqrtUnaireList(SqrtUnaireList object)
      {
        return createSqrtUnaireListAdapter();
      }
      @Override
      public Adapter caseSqrtUnaireNumber(SqrtUnaireNumber object)
      {
        return createSqrtUnaireNumberAdapter();
      }
      @Override
      public Adapter caseExpUnaire(ExpUnaire object)
      {
        return createExpUnaireAdapter();
      }
      @Override
      public Adapter caseExpUnaireList(ExpUnaireList object)
      {
        return createExpUnaireListAdapter();
      }
      @Override
      public Adapter caseExpUnaireNumber(ExpUnaireNumber object)
      {
        return createExpUnaireNumberAdapter();
      }
      @Override
      public Adapter caseSumBinaire(SumBinaire object)
      {
        return createSumBinaireAdapter();
      }
      @Override
      public Adapter caseSumBinaireListVal(SumBinaireListVal object)
      {
        return createSumBinaireListValAdapter();
      }
      @Override
      public Adapter caseSumBinaireListList(SumBinaireListList object)
      {
        return createSumBinaireListListAdapter();
      }
      @Override
      public Adapter caseSumBinaireValVal(SumBinaireValVal object)
      {
        return createSumBinaireValValAdapter();
      }
      @Override
      public Adapter caseProductBinaire(ProductBinaire object)
      {
        return createProductBinaireAdapter();
      }
      @Override
      public Adapter caseProductBinaireListVal(ProductBinaireListVal object)
      {
        return createProductBinaireListValAdapter();
      }
      @Override
      public Adapter caseProductBinaireListList(ProductBinaireListList object)
      {
        return createProductBinaireListListAdapter();
      }
      @Override
      public Adapter caseProductBinaireValVal(ProductBinaireValVal object)
      {
        return createProductBinaireValValAdapter();
      }
      @Override
      public Adapter caseDivisionBinaire(DivisionBinaire object)
      {
        return createDivisionBinaireAdapter();
      }
      @Override
      public Adapter caseDivisionBinaireListVal(DivisionBinaireListVal object)
      {
        return createDivisionBinaireListValAdapter();
      }
      @Override
      public Adapter caseDivisionBinaireValList(DivisionBinaireValList object)
      {
        return createDivisionBinaireValListAdapter();
      }
      @Override
      public Adapter caseDivisionBinaireListList(DivisionBinaireListList object)
      {
        return createDivisionBinaireListListAdapter();
      }
      @Override
      public Adapter caseDivisionBinaireValVal(DivisionBinaireValVal object)
      {
        return createDivisionBinaireValValAdapter();
      }
      @Override
      public Adapter caseMinBinaire(MinBinaire object)
      {
        return createMinBinaireAdapter();
      }
      @Override
      public Adapter caseMinBinaireListVal(MinBinaireListVal object)
      {
        return createMinBinaireListValAdapter();
      }
      @Override
      public Adapter caseMinBinaireListList(MinBinaireListList object)
      {
        return createMinBinaireListListAdapter();
      }
      @Override
      public Adapter caseMinBinaireValVal(MinBinaireValVal object)
      {
        return createMinBinaireValValAdapter();
      }
      @Override
      public Adapter caseMaxBinaire(MaxBinaire object)
      {
        return createMaxBinaireAdapter();
      }
      @Override
      public Adapter caseMaxBinaireListVal(MaxBinaireListVal object)
      {
        return createMaxBinaireListValAdapter();
      }
      @Override
      public Adapter caseMaxBinaireListList(MaxBinaireListList object)
      {
        return createMaxBinaireListListAdapter();
      }
      @Override
      public Adapter caseMaxBinaireValVal(MaxBinaireValVal object)
      {
        return createMaxBinaireValValAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.JavaSFT <em>Java SFT</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.JavaSFT
   * @generated
   */
  public Adapter createJavaSFTAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.TypeList <em>Type List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.TypeList
   * @generated
   */
  public Adapter createTypeListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.TypeListNumber <em>Type List Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.TypeListNumber
   * @generated
   */
  public Adapter createTypeListNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ClassName <em>Class Name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ClassName
   * @generated
   */
  public Adapter createClassNameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.Class
   * @generated
   */
  public Adapter createClassAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.Methode <em>Methode</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.Methode
   * @generated
   */
  public Adapter createMethodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.Parameter
   * @generated
   */
  public Adapter createParameterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.Return <em>Return</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.Return
   * @generated
   */
  public Adapter createReturnAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.Constant
   * @generated
   */
  public Adapter createConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ConstantDeclaration <em>Constant Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ConstantDeclaration
   * @generated
   */
  public Adapter createConstantDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ConstantAssignment <em>Constant Assignment</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ConstantAssignment
   * @generated
   */
  public Adapter createConstantAssignmentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.Operation
   * @generated
   */
  public Adapter createOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.OperationUnaire <em>Operation Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.OperationUnaire
   * @generated
   */
  public Adapter createOperationUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.OperationBinaire <em>Operation Binaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.OperationBinaire
   * @generated
   */
  public Adapter createOperationBinaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SumUnaire <em>Sum Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SumUnaire
   * @generated
   */
  public Adapter createSumUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ProductUnaire <em>Product Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ProductUnaire
   * @generated
   */
  public Adapter createProductUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MinUnaire <em>Min Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MinUnaire
   * @generated
   */
  public Adapter createMinUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MaxUnaire <em>Max Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MaxUnaire
   * @generated
   */
  public Adapter createMaxUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.OppositeUnaire <em>Opposite Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.OppositeUnaire
   * @generated
   */
  public Adapter createOppositeUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.OppositeUnaireList <em>Opposite Unaire List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.OppositeUnaireList
   * @generated
   */
  public Adapter createOppositeUnaireListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.OppositeUnaireNumber <em>Opposite Unaire Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.OppositeUnaireNumber
   * @generated
   */
  public Adapter createOppositeUnaireNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.CosUnaire <em>Cos Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.CosUnaire
   * @generated
   */
  public Adapter createCosUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.CosUnaireList <em>Cos Unaire List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.CosUnaireList
   * @generated
   */
  public Adapter createCosUnaireListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.CosUnaireNumber <em>Cos Unaire Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.CosUnaireNumber
   * @generated
   */
  public Adapter createCosUnaireNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SinUnaire <em>Sin Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SinUnaire
   * @generated
   */
  public Adapter createSinUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SinUnaireList <em>Sin Unaire List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SinUnaireList
   * @generated
   */
  public Adapter createSinUnaireListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SinUnaireNumber <em>Sin Unaire Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SinUnaireNumber
   * @generated
   */
  public Adapter createSinUnaireNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SqrtUnaire <em>Sqrt Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SqrtUnaire
   * @generated
   */
  public Adapter createSqrtUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SqrtUnaireList <em>Sqrt Unaire List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SqrtUnaireList
   * @generated
   */
  public Adapter createSqrtUnaireListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SqrtUnaireNumber <em>Sqrt Unaire Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SqrtUnaireNumber
   * @generated
   */
  public Adapter createSqrtUnaireNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ExpUnaire <em>Exp Unaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ExpUnaire
   * @generated
   */
  public Adapter createExpUnaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ExpUnaireList <em>Exp Unaire List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ExpUnaireList
   * @generated
   */
  public Adapter createExpUnaireListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ExpUnaireNumber <em>Exp Unaire Number</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ExpUnaireNumber
   * @generated
   */
  public Adapter createExpUnaireNumberAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SumBinaire <em>Sum Binaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SumBinaire
   * @generated
   */
  public Adapter createSumBinaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SumBinaireListVal <em>Sum Binaire List Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SumBinaireListVal
   * @generated
   */
  public Adapter createSumBinaireListValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SumBinaireListList <em>Sum Binaire List List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SumBinaireListList
   * @generated
   */
  public Adapter createSumBinaireListListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.SumBinaireValVal <em>Sum Binaire Val Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.SumBinaireValVal
   * @generated
   */
  public Adapter createSumBinaireValValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ProductBinaire <em>Product Binaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ProductBinaire
   * @generated
   */
  public Adapter createProductBinaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ProductBinaireListVal <em>Product Binaire List Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ProductBinaireListVal
   * @generated
   */
  public Adapter createProductBinaireListValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ProductBinaireListList <em>Product Binaire List List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ProductBinaireListList
   * @generated
   */
  public Adapter createProductBinaireListListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.ProductBinaireValVal <em>Product Binaire Val Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.ProductBinaireValVal
   * @generated
   */
  public Adapter createProductBinaireValValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.DivisionBinaire <em>Division Binaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.DivisionBinaire
   * @generated
   */
  public Adapter createDivisionBinaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.DivisionBinaireListVal <em>Division Binaire List Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.DivisionBinaireListVal
   * @generated
   */
  public Adapter createDivisionBinaireListValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.DivisionBinaireValList <em>Division Binaire Val List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.DivisionBinaireValList
   * @generated
   */
  public Adapter createDivisionBinaireValListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.DivisionBinaireListList <em>Division Binaire List List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.DivisionBinaireListList
   * @generated
   */
  public Adapter createDivisionBinaireListListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.DivisionBinaireValVal <em>Division Binaire Val Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.DivisionBinaireValVal
   * @generated
   */
  public Adapter createDivisionBinaireValValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MinBinaire <em>Min Binaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MinBinaire
   * @generated
   */
  public Adapter createMinBinaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MinBinaireListVal <em>Min Binaire List Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MinBinaireListVal
   * @generated
   */
  public Adapter createMinBinaireListValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MinBinaireListList <em>Min Binaire List List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MinBinaireListList
   * @generated
   */
  public Adapter createMinBinaireListListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MinBinaireValVal <em>Min Binaire Val Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MinBinaireValVal
   * @generated
   */
  public Adapter createMinBinaireValValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MaxBinaire <em>Max Binaire</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MaxBinaire
   * @generated
   */
  public Adapter createMaxBinaireAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MaxBinaireListVal <em>Max Binaire List Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MaxBinaireListVal
   * @generated
   */
  public Adapter createMaxBinaireListValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MaxBinaireListList <em>Max Binaire List List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MaxBinaireListList
   * @generated
   */
  public Adapter createMaxBinaireListListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link projetIDM.javaSFT.MaxBinaireValVal <em>Max Binaire Val Val</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see projetIDM.javaSFT.MaxBinaireValVal
   * @generated
   */
  public Adapter createMaxBinaireValValAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //JavaSFTAdapterFactory
