/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import projetIDM.javaSFT.ClassName;
import projetIDM.javaSFT.Constant;
import projetIDM.javaSFT.ConstantAssignment;
import projetIDM.javaSFT.ConstantDeclaration;
import projetIDM.javaSFT.CosUnaire;
import projetIDM.javaSFT.CosUnaireList;
import projetIDM.javaSFT.CosUnaireNumber;
import projetIDM.javaSFT.DivisionBinaire;
import projetIDM.javaSFT.DivisionBinaireListList;
import projetIDM.javaSFT.DivisionBinaireListVal;
import projetIDM.javaSFT.DivisionBinaireValList;
import projetIDM.javaSFT.DivisionBinaireValVal;
import projetIDM.javaSFT.ExpUnaire;
import projetIDM.javaSFT.ExpUnaireList;
import projetIDM.javaSFT.ExpUnaireNumber;
import projetIDM.javaSFT.JavaSFT;
import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.MaxBinaire;
import projetIDM.javaSFT.MaxBinaireListList;
import projetIDM.javaSFT.MaxBinaireListVal;
import projetIDM.javaSFT.MaxBinaireValVal;
import projetIDM.javaSFT.MaxUnaire;
import projetIDM.javaSFT.Methode;
import projetIDM.javaSFT.MinBinaire;
import projetIDM.javaSFT.MinBinaireListList;
import projetIDM.javaSFT.MinBinaireListVal;
import projetIDM.javaSFT.MinBinaireValVal;
import projetIDM.javaSFT.MinUnaire;
import projetIDM.javaSFT.Operation;
import projetIDM.javaSFT.OperationBinaire;
import projetIDM.javaSFT.OperationUnaire;
import projetIDM.javaSFT.OppositeUnaire;
import projetIDM.javaSFT.OppositeUnaireList;
import projetIDM.javaSFT.OppositeUnaireNumber;
import projetIDM.javaSFT.Parameter;
import projetIDM.javaSFT.ProductBinaire;
import projetIDM.javaSFT.ProductBinaireListList;
import projetIDM.javaSFT.ProductBinaireListVal;
import projetIDM.javaSFT.ProductBinaireValVal;
import projetIDM.javaSFT.ProductUnaire;
import projetIDM.javaSFT.Return;
import projetIDM.javaSFT.SinUnaire;
import projetIDM.javaSFT.SinUnaireList;
import projetIDM.javaSFT.SinUnaireNumber;
import projetIDM.javaSFT.SqrtUnaire;
import projetIDM.javaSFT.SqrtUnaireList;
import projetIDM.javaSFT.SqrtUnaireNumber;
import projetIDM.javaSFT.SumBinaire;
import projetIDM.javaSFT.SumBinaireListList;
import projetIDM.javaSFT.SumBinaireListVal;
import projetIDM.javaSFT.SumBinaireValVal;
import projetIDM.javaSFT.SumUnaire;
import projetIDM.javaSFT.TypeList;
import projetIDM.javaSFT.TypeListNumber;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see projetIDM.javaSFT.JavaSFTPackage
 * @generated
 */
public class JavaSFTSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static JavaSFTPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JavaSFTSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = JavaSFTPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case JavaSFTPackage.JAVA_SFT:
      {
        JavaSFT javaSFT = (JavaSFT)theEObject;
        T result = caseJavaSFT(javaSFT);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.TYPE_LIST:
      {
        TypeList typeList = (TypeList)theEObject;
        T result = caseTypeList(typeList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.TYPE_LIST_NUMBER:
      {
        TypeListNumber typeListNumber = (TypeListNumber)theEObject;
        T result = caseTypeListNumber(typeListNumber);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.CLASS_NAME:
      {
        ClassName className = (ClassName)theEObject;
        T result = caseClassName(className);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.CLASS:
      {
        projetIDM.javaSFT.Class class_ = (projetIDM.javaSFT.Class)theEObject;
        T result = caseClass(class_);
        if (result == null) result = caseJavaSFT(class_);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.METHODE:
      {
        Methode methode = (Methode)theEObject;
        T result = caseMethode(methode);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.PARAMETER:
      {
        Parameter parameter = (Parameter)theEObject;
        T result = caseParameter(parameter);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.RETURN:
      {
        Return return_ = (Return)theEObject;
        T result = caseReturn(return_);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.CONSTANT:
      {
        Constant constant = (Constant)theEObject;
        T result = caseConstant(constant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.CONSTANT_DECLARATION:
      {
        ConstantDeclaration constantDeclaration = (ConstantDeclaration)theEObject;
        T result = caseConstantDeclaration(constantDeclaration);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.CONSTANT_ASSIGNMENT:
      {
        ConstantAssignment constantAssignment = (ConstantAssignment)theEObject;
        T result = caseConstantAssignment(constantAssignment);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.OPERATION:
      {
        Operation operation = (Operation)theEObject;
        T result = caseOperation(operation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.OPERATION_UNAIRE:
      {
        OperationUnaire operationUnaire = (OperationUnaire)theEObject;
        T result = caseOperationUnaire(operationUnaire);
        if (result == null) result = caseOperation(operationUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.OPERATION_BINAIRE:
      {
        OperationBinaire operationBinaire = (OperationBinaire)theEObject;
        T result = caseOperationBinaire(operationBinaire);
        if (result == null) result = caseOperation(operationBinaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SUM_UNAIRE:
      {
        SumUnaire sumUnaire = (SumUnaire)theEObject;
        T result = caseSumUnaire(sumUnaire);
        if (result == null) result = caseOperationUnaire(sumUnaire);
        if (result == null) result = caseOperation(sumUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.PRODUCT_UNAIRE:
      {
        ProductUnaire productUnaire = (ProductUnaire)theEObject;
        T result = caseProductUnaire(productUnaire);
        if (result == null) result = caseOperationUnaire(productUnaire);
        if (result == null) result = caseOperation(productUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MIN_UNAIRE:
      {
        MinUnaire minUnaire = (MinUnaire)theEObject;
        T result = caseMinUnaire(minUnaire);
        if (result == null) result = caseOperationUnaire(minUnaire);
        if (result == null) result = caseOperation(minUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MAX_UNAIRE:
      {
        MaxUnaire maxUnaire = (MaxUnaire)theEObject;
        T result = caseMaxUnaire(maxUnaire);
        if (result == null) result = caseOperationUnaire(maxUnaire);
        if (result == null) result = caseOperation(maxUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.OPPOSITE_UNAIRE:
      {
        OppositeUnaire oppositeUnaire = (OppositeUnaire)theEObject;
        T result = caseOppositeUnaire(oppositeUnaire);
        if (result == null) result = caseOperationUnaire(oppositeUnaire);
        if (result == null) result = caseOperation(oppositeUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.OPPOSITE_UNAIRE_LIST:
      {
        OppositeUnaireList oppositeUnaireList = (OppositeUnaireList)theEObject;
        T result = caseOppositeUnaireList(oppositeUnaireList);
        if (result == null) result = caseOppositeUnaire(oppositeUnaireList);
        if (result == null) result = caseOperationUnaire(oppositeUnaireList);
        if (result == null) result = caseOperation(oppositeUnaireList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.OPPOSITE_UNAIRE_NUMBER:
      {
        OppositeUnaireNumber oppositeUnaireNumber = (OppositeUnaireNumber)theEObject;
        T result = caseOppositeUnaireNumber(oppositeUnaireNumber);
        if (result == null) result = caseOppositeUnaire(oppositeUnaireNumber);
        if (result == null) result = caseOperationUnaire(oppositeUnaireNumber);
        if (result == null) result = caseOperation(oppositeUnaireNumber);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.COS_UNAIRE:
      {
        CosUnaire cosUnaire = (CosUnaire)theEObject;
        T result = caseCosUnaire(cosUnaire);
        if (result == null) result = caseOperationUnaire(cosUnaire);
        if (result == null) result = caseOperation(cosUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.COS_UNAIRE_LIST:
      {
        CosUnaireList cosUnaireList = (CosUnaireList)theEObject;
        T result = caseCosUnaireList(cosUnaireList);
        if (result == null) result = caseCosUnaire(cosUnaireList);
        if (result == null) result = caseOperationUnaire(cosUnaireList);
        if (result == null) result = caseOperation(cosUnaireList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.COS_UNAIRE_NUMBER:
      {
        CosUnaireNumber cosUnaireNumber = (CosUnaireNumber)theEObject;
        T result = caseCosUnaireNumber(cosUnaireNumber);
        if (result == null) result = caseCosUnaire(cosUnaireNumber);
        if (result == null) result = caseOperationUnaire(cosUnaireNumber);
        if (result == null) result = caseOperation(cosUnaireNumber);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SIN_UNAIRE:
      {
        SinUnaire sinUnaire = (SinUnaire)theEObject;
        T result = caseSinUnaire(sinUnaire);
        if (result == null) result = caseOperationUnaire(sinUnaire);
        if (result == null) result = caseOperation(sinUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SIN_UNAIRE_LIST:
      {
        SinUnaireList sinUnaireList = (SinUnaireList)theEObject;
        T result = caseSinUnaireList(sinUnaireList);
        if (result == null) result = caseSinUnaire(sinUnaireList);
        if (result == null) result = caseOperationUnaire(sinUnaireList);
        if (result == null) result = caseOperation(sinUnaireList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SIN_UNAIRE_NUMBER:
      {
        SinUnaireNumber sinUnaireNumber = (SinUnaireNumber)theEObject;
        T result = caseSinUnaireNumber(sinUnaireNumber);
        if (result == null) result = caseSinUnaire(sinUnaireNumber);
        if (result == null) result = caseOperationUnaire(sinUnaireNumber);
        if (result == null) result = caseOperation(sinUnaireNumber);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SQRT_UNAIRE:
      {
        SqrtUnaire sqrtUnaire = (SqrtUnaire)theEObject;
        T result = caseSqrtUnaire(sqrtUnaire);
        if (result == null) result = caseOperationUnaire(sqrtUnaire);
        if (result == null) result = caseOperation(sqrtUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SQRT_UNAIRE_LIST:
      {
        SqrtUnaireList sqrtUnaireList = (SqrtUnaireList)theEObject;
        T result = caseSqrtUnaireList(sqrtUnaireList);
        if (result == null) result = caseSqrtUnaire(sqrtUnaireList);
        if (result == null) result = caseOperationUnaire(sqrtUnaireList);
        if (result == null) result = caseOperation(sqrtUnaireList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SQRT_UNAIRE_NUMBER:
      {
        SqrtUnaireNumber sqrtUnaireNumber = (SqrtUnaireNumber)theEObject;
        T result = caseSqrtUnaireNumber(sqrtUnaireNumber);
        if (result == null) result = caseSqrtUnaire(sqrtUnaireNumber);
        if (result == null) result = caseOperationUnaire(sqrtUnaireNumber);
        if (result == null) result = caseOperation(sqrtUnaireNumber);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.EXP_UNAIRE:
      {
        ExpUnaire expUnaire = (ExpUnaire)theEObject;
        T result = caseExpUnaire(expUnaire);
        if (result == null) result = caseOperationUnaire(expUnaire);
        if (result == null) result = caseOperation(expUnaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.EXP_UNAIRE_LIST:
      {
        ExpUnaireList expUnaireList = (ExpUnaireList)theEObject;
        T result = caseExpUnaireList(expUnaireList);
        if (result == null) result = caseExpUnaire(expUnaireList);
        if (result == null) result = caseOperationUnaire(expUnaireList);
        if (result == null) result = caseOperation(expUnaireList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.EXP_UNAIRE_NUMBER:
      {
        ExpUnaireNumber expUnaireNumber = (ExpUnaireNumber)theEObject;
        T result = caseExpUnaireNumber(expUnaireNumber);
        if (result == null) result = caseExpUnaire(expUnaireNumber);
        if (result == null) result = caseOperationUnaire(expUnaireNumber);
        if (result == null) result = caseOperation(expUnaireNumber);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SUM_BINAIRE:
      {
        SumBinaire sumBinaire = (SumBinaire)theEObject;
        T result = caseSumBinaire(sumBinaire);
        if (result == null) result = caseOperationBinaire(sumBinaire);
        if (result == null) result = caseOperation(sumBinaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SUM_BINAIRE_LIST_VAL:
      {
        SumBinaireListVal sumBinaireListVal = (SumBinaireListVal)theEObject;
        T result = caseSumBinaireListVal(sumBinaireListVal);
        if (result == null) result = caseSumBinaire(sumBinaireListVal);
        if (result == null) result = caseOperationBinaire(sumBinaireListVal);
        if (result == null) result = caseOperation(sumBinaireListVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SUM_BINAIRE_LIST_LIST:
      {
        SumBinaireListList sumBinaireListList = (SumBinaireListList)theEObject;
        T result = caseSumBinaireListList(sumBinaireListList);
        if (result == null) result = caseSumBinaire(sumBinaireListList);
        if (result == null) result = caseOperationBinaire(sumBinaireListList);
        if (result == null) result = caseOperation(sumBinaireListList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL:
      {
        SumBinaireValVal sumBinaireValVal = (SumBinaireValVal)theEObject;
        T result = caseSumBinaireValVal(sumBinaireValVal);
        if (result == null) result = caseSumBinaire(sumBinaireValVal);
        if (result == null) result = caseOperationBinaire(sumBinaireValVal);
        if (result == null) result = caseOperation(sumBinaireValVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.PRODUCT_BINAIRE:
      {
        ProductBinaire productBinaire = (ProductBinaire)theEObject;
        T result = caseProductBinaire(productBinaire);
        if (result == null) result = caseOperationBinaire(productBinaire);
        if (result == null) result = caseOperation(productBinaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.PRODUCT_BINAIRE_LIST_VAL:
      {
        ProductBinaireListVal productBinaireListVal = (ProductBinaireListVal)theEObject;
        T result = caseProductBinaireListVal(productBinaireListVal);
        if (result == null) result = caseProductBinaire(productBinaireListVal);
        if (result == null) result = caseOperationBinaire(productBinaireListVal);
        if (result == null) result = caseOperation(productBinaireListVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.PRODUCT_BINAIRE_LIST_LIST:
      {
        ProductBinaireListList productBinaireListList = (ProductBinaireListList)theEObject;
        T result = caseProductBinaireListList(productBinaireListList);
        if (result == null) result = caseProductBinaire(productBinaireListList);
        if (result == null) result = caseOperationBinaire(productBinaireListList);
        if (result == null) result = caseOperation(productBinaireListList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.PRODUCT_BINAIRE_VAL_VAL:
      {
        ProductBinaireValVal productBinaireValVal = (ProductBinaireValVal)theEObject;
        T result = caseProductBinaireValVal(productBinaireValVal);
        if (result == null) result = caseProductBinaire(productBinaireValVal);
        if (result == null) result = caseOperationBinaire(productBinaireValVal);
        if (result == null) result = caseOperation(productBinaireValVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.DIVISION_BINAIRE:
      {
        DivisionBinaire divisionBinaire = (DivisionBinaire)theEObject;
        T result = caseDivisionBinaire(divisionBinaire);
        if (result == null) result = caseOperationBinaire(divisionBinaire);
        if (result == null) result = caseOperation(divisionBinaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL:
      {
        DivisionBinaireListVal divisionBinaireListVal = (DivisionBinaireListVal)theEObject;
        T result = caseDivisionBinaireListVal(divisionBinaireListVal);
        if (result == null) result = caseDivisionBinaire(divisionBinaireListVal);
        if (result == null) result = caseOperationBinaire(divisionBinaireListVal);
        if (result == null) result = caseOperation(divisionBinaireListVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.DIVISION_BINAIRE_VAL_LIST:
      {
        DivisionBinaireValList divisionBinaireValList = (DivisionBinaireValList)theEObject;
        T result = caseDivisionBinaireValList(divisionBinaireValList);
        if (result == null) result = caseDivisionBinaire(divisionBinaireValList);
        if (result == null) result = caseOperationBinaire(divisionBinaireValList);
        if (result == null) result = caseOperation(divisionBinaireValList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_LIST:
      {
        DivisionBinaireListList divisionBinaireListList = (DivisionBinaireListList)theEObject;
        T result = caseDivisionBinaireListList(divisionBinaireListList);
        if (result == null) result = caseDivisionBinaire(divisionBinaireListList);
        if (result == null) result = caseOperationBinaire(divisionBinaireListList);
        if (result == null) result = caseOperation(divisionBinaireListList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.DIVISION_BINAIRE_VAL_VAL:
      {
        DivisionBinaireValVal divisionBinaireValVal = (DivisionBinaireValVal)theEObject;
        T result = caseDivisionBinaireValVal(divisionBinaireValVal);
        if (result == null) result = caseDivisionBinaire(divisionBinaireValVal);
        if (result == null) result = caseOperationBinaire(divisionBinaireValVal);
        if (result == null) result = caseOperation(divisionBinaireValVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MIN_BINAIRE:
      {
        MinBinaire minBinaire = (MinBinaire)theEObject;
        T result = caseMinBinaire(minBinaire);
        if (result == null) result = caseOperationBinaire(minBinaire);
        if (result == null) result = caseOperation(minBinaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MIN_BINAIRE_LIST_VAL:
      {
        MinBinaireListVal minBinaireListVal = (MinBinaireListVal)theEObject;
        T result = caseMinBinaireListVal(minBinaireListVal);
        if (result == null) result = caseMinBinaire(minBinaireListVal);
        if (result == null) result = caseOperationBinaire(minBinaireListVal);
        if (result == null) result = caseOperation(minBinaireListVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MIN_BINAIRE_LIST_LIST:
      {
        MinBinaireListList minBinaireListList = (MinBinaireListList)theEObject;
        T result = caseMinBinaireListList(minBinaireListList);
        if (result == null) result = caseMinBinaire(minBinaireListList);
        if (result == null) result = caseOperationBinaire(minBinaireListList);
        if (result == null) result = caseOperation(minBinaireListList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MIN_BINAIRE_VAL_VAL:
      {
        MinBinaireValVal minBinaireValVal = (MinBinaireValVal)theEObject;
        T result = caseMinBinaireValVal(minBinaireValVal);
        if (result == null) result = caseMinBinaire(minBinaireValVal);
        if (result == null) result = caseOperationBinaire(minBinaireValVal);
        if (result == null) result = caseOperation(minBinaireValVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MAX_BINAIRE:
      {
        MaxBinaire maxBinaire = (MaxBinaire)theEObject;
        T result = caseMaxBinaire(maxBinaire);
        if (result == null) result = caseOperationBinaire(maxBinaire);
        if (result == null) result = caseOperation(maxBinaire);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MAX_BINAIRE_LIST_VAL:
      {
        MaxBinaireListVal maxBinaireListVal = (MaxBinaireListVal)theEObject;
        T result = caseMaxBinaireListVal(maxBinaireListVal);
        if (result == null) result = caseMaxBinaire(maxBinaireListVal);
        if (result == null) result = caseOperationBinaire(maxBinaireListVal);
        if (result == null) result = caseOperation(maxBinaireListVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MAX_BINAIRE_LIST_LIST:
      {
        MaxBinaireListList maxBinaireListList = (MaxBinaireListList)theEObject;
        T result = caseMaxBinaireListList(maxBinaireListList);
        if (result == null) result = caseMaxBinaire(maxBinaireListList);
        if (result == null) result = caseOperationBinaire(maxBinaireListList);
        if (result == null) result = caseOperation(maxBinaireListList);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case JavaSFTPackage.MAX_BINAIRE_VAL_VAL:
      {
        MaxBinaireValVal maxBinaireValVal = (MaxBinaireValVal)theEObject;
        T result = caseMaxBinaireValVal(maxBinaireValVal);
        if (result == null) result = caseMaxBinaire(maxBinaireValVal);
        if (result == null) result = caseOperationBinaire(maxBinaireValVal);
        if (result == null) result = caseOperation(maxBinaireValVal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Java SFT</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Java SFT</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseJavaSFT(JavaSFT object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Type List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Type List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTypeList(TypeList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Type List Number</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Type List Number</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTypeListNumber(TypeListNumber object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Class Name</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Class Name</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseClassName(ClassName object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Class</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Class</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseClass(projetIDM.javaSFT.Class object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Methode</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Methode</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMethode(Methode object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Parameter</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Parameter</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseParameter(Parameter object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Return</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Return</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReturn(Return object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstant(Constant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constant Declaration</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constant Declaration</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstantDeclaration(ConstantDeclaration object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constant Assignment</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constant Assignment</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstantAssignment(ConstantAssignment object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperation(Operation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operation Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operation Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperationUnaire(OperationUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Operation Binaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Operation Binaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOperationBinaire(OperationBinaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sum Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sum Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSumUnaire(SumUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Product Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Product Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProductUnaire(ProductUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Min Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Min Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMinUnaire(MinUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Max Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Max Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaxUnaire(MaxUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Opposite Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Opposite Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOppositeUnaire(OppositeUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Opposite Unaire List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Opposite Unaire List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOppositeUnaireList(OppositeUnaireList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Opposite Unaire Number</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Opposite Unaire Number</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOppositeUnaireNumber(OppositeUnaireNumber object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Cos Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Cos Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCosUnaire(CosUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Cos Unaire List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Cos Unaire List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCosUnaireList(CosUnaireList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Cos Unaire Number</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Cos Unaire Number</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCosUnaireNumber(CosUnaireNumber object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sin Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sin Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSinUnaire(SinUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sin Unaire List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sin Unaire List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSinUnaireList(SinUnaireList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sin Unaire Number</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sin Unaire Number</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSinUnaireNumber(SinUnaireNumber object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sqrt Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sqrt Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSqrtUnaire(SqrtUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sqrt Unaire List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sqrt Unaire List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSqrtUnaireList(SqrtUnaireList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sqrt Unaire Number</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sqrt Unaire Number</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSqrtUnaireNumber(SqrtUnaireNumber object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Exp Unaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Exp Unaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpUnaire(ExpUnaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Exp Unaire List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Exp Unaire List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpUnaireList(ExpUnaireList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Exp Unaire Number</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Exp Unaire Number</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpUnaireNumber(ExpUnaireNumber object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sum Binaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sum Binaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSumBinaire(SumBinaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sum Binaire List Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sum Binaire List Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSumBinaireListVal(SumBinaireListVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sum Binaire List List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sum Binaire List List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSumBinaireListList(SumBinaireListList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sum Binaire Val Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sum Binaire Val Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSumBinaireValVal(SumBinaireValVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Product Binaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Product Binaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProductBinaire(ProductBinaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Product Binaire List Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Product Binaire List Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProductBinaireListVal(ProductBinaireListVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Product Binaire List List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Product Binaire List List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProductBinaireListList(ProductBinaireListList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Product Binaire Val Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Product Binaire Val Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProductBinaireValVal(ProductBinaireValVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Division Binaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Division Binaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDivisionBinaire(DivisionBinaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Division Binaire List Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Division Binaire List Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDivisionBinaireListVal(DivisionBinaireListVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Division Binaire Val List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Division Binaire Val List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDivisionBinaireValList(DivisionBinaireValList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Division Binaire List List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Division Binaire List List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDivisionBinaireListList(DivisionBinaireListList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Division Binaire Val Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Division Binaire Val Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDivisionBinaireValVal(DivisionBinaireValVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Min Binaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Min Binaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMinBinaire(MinBinaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Min Binaire List Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Min Binaire List Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMinBinaireListVal(MinBinaireListVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Min Binaire List List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Min Binaire List List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMinBinaireListList(MinBinaireListList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Min Binaire Val Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Min Binaire Val Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMinBinaireValVal(MinBinaireValVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Max Binaire</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Max Binaire</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaxBinaire(MaxBinaire object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Max Binaire List Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Max Binaire List Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaxBinaireListVal(MaxBinaireListVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Max Binaire List List</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Max Binaire List List</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaxBinaireListList(MaxBinaireListList object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Max Binaire Val Val</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Max Binaire Val Val</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMaxBinaireValVal(MaxBinaireValVal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //JavaSFTSwitch
