/**
 * generated by Xtext 2.37.0
 */
package projetIDM.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(JavaSFTInjectorProvider.class)
@SuppressWarnings("all")
public class JavaSFTParsingTest {
  @Inject
  private /* ParseHelper<JavaSFTM> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field JavaSFTParsingTest.parseHelper refers to the missing type JavaSFTM"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
