/*
 * generated by Xtext 2.37.0
 */
package projetIDM.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import projetIDM.JavaSFTRuntimeModule;
import projetIDM.JavaSFTStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JavaSFTIdeSetup extends JavaSFTStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JavaSFTRuntimeModule(), new JavaSFTIdeModule()));
	}
	
}
