/*
 * generated by Xtext 2.37.0
 */
package projetIDM.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJavaSFTScopeProvider extends DelegatingScopeProvider {
}
