/*
 * generated by Xtext 2.37.0
 */
package projetIDM.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import projetIDM.javaSFT.ClassName;
import projetIDM.javaSFT.Constant;
import projetIDM.javaSFT.ConstantAssignment;
import projetIDM.javaSFT.ConstantDeclaration;
import projetIDM.javaSFT.CosUnaireList;
import projetIDM.javaSFT.CosUnaireNumber;
import projetIDM.javaSFT.DivisionBinaireListList;
import projetIDM.javaSFT.DivisionBinaireListVal;
import projetIDM.javaSFT.DivisionBinaireValList;
import projetIDM.javaSFT.DivisionBinaireValVal;
import projetIDM.javaSFT.ExpUnaireList;
import projetIDM.javaSFT.ExpUnaireNumber;
import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.MaxBinaireListList;
import projetIDM.javaSFT.MaxBinaireListVal;
import projetIDM.javaSFT.MaxBinaireValVal;
import projetIDM.javaSFT.MaxUnaire;
import projetIDM.javaSFT.Methode;
import projetIDM.javaSFT.MinBinaireListList;
import projetIDM.javaSFT.MinBinaireListVal;
import projetIDM.javaSFT.MinBinaireValVal;
import projetIDM.javaSFT.MinUnaire;
import projetIDM.javaSFT.OppositeUnaireList;
import projetIDM.javaSFT.OppositeUnaireNumber;
import projetIDM.javaSFT.ProductBinaireListList;
import projetIDM.javaSFT.ProductBinaireListVal;
import projetIDM.javaSFT.ProductBinaireValVal;
import projetIDM.javaSFT.ProductUnaire;
import projetIDM.javaSFT.Return;
import projetIDM.javaSFT.SinUnaireList;
import projetIDM.javaSFT.SinUnaireNumber;
import projetIDM.javaSFT.SqrtUnaireList;
import projetIDM.javaSFT.SqrtUnaireNumber;
import projetIDM.javaSFT.SumBinaireListList;
import projetIDM.javaSFT.SumBinaireListVal;
import projetIDM.javaSFT.SumBinaireValVal;
import projetIDM.javaSFT.SumUnaire;
import projetIDM.javaSFT.TypeList;
import projetIDM.javaSFT.TypeListNumber;
import projetIDM.services.JavaSFTGrammarAccess;

@SuppressWarnings("all")
public class JavaSFTSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private JavaSFTGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == JavaSFTPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case JavaSFTPackage.CLASS:
				sequence_Class(context, (projetIDM.javaSFT.Class) semanticObject); 
				return; 
			case JavaSFTPackage.CLASS_NAME:
				sequence_ClassName(context, (ClassName) semanticObject); 
				return; 
			case JavaSFTPackage.CONSTANT:
				sequence_Constant(context, (Constant) semanticObject); 
				return; 
			case JavaSFTPackage.CONSTANT_ASSIGNMENT:
				sequence_ConstantAssignment(context, (ConstantAssignment) semanticObject); 
				return; 
			case JavaSFTPackage.CONSTANT_DECLARATION:
				sequence_ConstantDeclaration(context, (ConstantDeclaration) semanticObject); 
				return; 
			case JavaSFTPackage.COS_UNAIRE_LIST:
				sequence_CosUnaireList(context, (CosUnaireList) semanticObject); 
				return; 
			case JavaSFTPackage.COS_UNAIRE_NUMBER:
				sequence_CosUnaireNumber(context, (CosUnaireNumber) semanticObject); 
				return; 
			case JavaSFTPackage.DIVISION_BINAIRE_LIST_LIST:
				sequence_DivisionBinaireListList(context, (DivisionBinaireListList) semanticObject); 
				return; 
			case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL:
				sequence_DivisionBinaireListVal(context, (DivisionBinaireListVal) semanticObject); 
				return; 
			case JavaSFTPackage.DIVISION_BINAIRE_VAL_LIST:
				sequence_DivisionBinaireValList(context, (DivisionBinaireValList) semanticObject); 
				return; 
			case JavaSFTPackage.DIVISION_BINAIRE_VAL_VAL:
				sequence_DivisionBinaireValVal(context, (DivisionBinaireValVal) semanticObject); 
				return; 
			case JavaSFTPackage.EXP_UNAIRE_LIST:
				sequence_ExpUnaireList(context, (ExpUnaireList) semanticObject); 
				return; 
			case JavaSFTPackage.EXP_UNAIRE_NUMBER:
				sequence_ExpUnaireNumber(context, (ExpUnaireNumber) semanticObject); 
				return; 
			case JavaSFTPackage.MAX_BINAIRE_LIST_LIST:
				sequence_MaxBinaireListList(context, (MaxBinaireListList) semanticObject); 
				return; 
			case JavaSFTPackage.MAX_BINAIRE_LIST_VAL:
				sequence_MaxBinaireListVal(context, (MaxBinaireListVal) semanticObject); 
				return; 
			case JavaSFTPackage.MAX_BINAIRE_VAL_VAL:
				sequence_MaxBinaireValVal(context, (MaxBinaireValVal) semanticObject); 
				return; 
			case JavaSFTPackage.MAX_UNAIRE:
				sequence_MaxUnaire(context, (MaxUnaire) semanticObject); 
				return; 
			case JavaSFTPackage.METHODE:
				sequence_Methode(context, (Methode) semanticObject); 
				return; 
			case JavaSFTPackage.MIN_BINAIRE_LIST_LIST:
				sequence_MinBinaireListList(context, (MinBinaireListList) semanticObject); 
				return; 
			case JavaSFTPackage.MIN_BINAIRE_LIST_VAL:
				sequence_MinBinaireListVal(context, (MinBinaireListVal) semanticObject); 
				return; 
			case JavaSFTPackage.MIN_BINAIRE_VAL_VAL:
				sequence_MinBinaireValVal(context, (MinBinaireValVal) semanticObject); 
				return; 
			case JavaSFTPackage.MIN_UNAIRE:
				sequence_MinUnaire(context, (MinUnaire) semanticObject); 
				return; 
			case JavaSFTPackage.OPPOSITE_UNAIRE_LIST:
				sequence_OppositeUnaireList(context, (OppositeUnaireList) semanticObject); 
				return; 
			case JavaSFTPackage.OPPOSITE_UNAIRE_NUMBER:
				sequence_OppositeUnaireNumber(context, (OppositeUnaireNumber) semanticObject); 
				return; 
			case JavaSFTPackage.PARAMETER:
				sequence_Parameter(context, (projetIDM.javaSFT.Parameter) semanticObject); 
				return; 
			case JavaSFTPackage.PRODUCT_BINAIRE_LIST_LIST:
				sequence_ProductBinaireListList(context, (ProductBinaireListList) semanticObject); 
				return; 
			case JavaSFTPackage.PRODUCT_BINAIRE_LIST_VAL:
				sequence_ProductBinaireListVal(context, (ProductBinaireListVal) semanticObject); 
				return; 
			case JavaSFTPackage.PRODUCT_BINAIRE_VAL_VAL:
				sequence_ProductBinaireValVal(context, (ProductBinaireValVal) semanticObject); 
				return; 
			case JavaSFTPackage.PRODUCT_UNAIRE:
				sequence_ProductUnaire(context, (ProductUnaire) semanticObject); 
				return; 
			case JavaSFTPackage.RETURN:
				sequence_Return(context, (Return) semanticObject); 
				return; 
			case JavaSFTPackage.SIN_UNAIRE_LIST:
				sequence_SinUnaireList(context, (SinUnaireList) semanticObject); 
				return; 
			case JavaSFTPackage.SIN_UNAIRE_NUMBER:
				sequence_SinUnaireNumber(context, (SinUnaireNumber) semanticObject); 
				return; 
			case JavaSFTPackage.SQRT_UNAIRE_LIST:
				sequence_SqrtUnaireList(context, (SqrtUnaireList) semanticObject); 
				return; 
			case JavaSFTPackage.SQRT_UNAIRE_NUMBER:
				sequence_SqrtUnaireNumber(context, (SqrtUnaireNumber) semanticObject); 
				return; 
			case JavaSFTPackage.SUM_BINAIRE_LIST_LIST:
				sequence_SumBinaireListList(context, (SumBinaireListList) semanticObject); 
				return; 
			case JavaSFTPackage.SUM_BINAIRE_LIST_VAL:
				sequence_SumBinaireListVal(context, (SumBinaireListVal) semanticObject); 
				return; 
			case JavaSFTPackage.SUM_BINAIRE_VAL_VAL:
				sequence_SumBinaireValVal(context, (SumBinaireValVal) semanticObject); 
				return; 
			case JavaSFTPackage.SUM_UNAIRE:
				sequence_SumUnaire(context, (SumUnaire) semanticObject); 
				return; 
			case JavaSFTPackage.TYPE_LIST:
				sequence_TypeList(context, (TypeList) semanticObject); 
				return; 
			case JavaSFTPackage.TYPE_LIST_NUMBER:
				sequence_TypeListNumber(context, (TypeListNumber) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     ClassName returns ClassName
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_ClassName(ISerializationContext context, ClassName semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CLASS_NAME__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CLASS_NAME__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getClassNameAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     JavaSFT returns Class
	 *     Class returns Class
	 *
	 * Constraint:
	 *     (className=ClassName methode=Methode)
	 * </pre>
	 */
	protected void sequence_Class(ISerializationContext context, projetIDM.javaSFT.Class semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CLASS__CLASS_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CLASS__CLASS_NAME));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CLASS__METHODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CLASS__METHODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getClassAccess().getClassNameClassNameParserRuleCall_2_0(), semanticObject.getClassName());
		feeder.accept(grammarAccess.getClassAccess().getMethodeMethodeParserRuleCall_4_0(), semanticObject.getMethode());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ConstantAssignment returns ConstantAssignment
	 *
	 * Constraint:
	 *     value=Value
	 * </pre>
	 */
	protected void sequence_ConstantAssignment(ISerializationContext context, ConstantAssignment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CONSTANT_ASSIGNMENT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CONSTANT_ASSIGNMENT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstantAssignmentAccess().getValueValueParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ConstantDeclaration returns ConstantDeclaration
	 *
	 * Constraint:
	 *     (type=Type varName=ID)
	 * </pre>
	 */
	protected void sequence_ConstantDeclaration(ISerializationContext context, ConstantDeclaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CONSTANT_DECLARATION__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CONSTANT_DECLARATION__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CONSTANT_DECLARATION__VAR_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CONSTANT_DECLARATION__VAR_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstantDeclarationAccess().getTypeTypeParserRuleCall_1_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getConstantDeclarationAccess().getVarNameIDTerminalRuleCall_2_0(), semanticObject.getVarName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Constant returns Constant
	 *
	 * Constraint:
	 *     (constDeclaration=ConstantDeclaration constAssignment=ConstantAssignment)
	 * </pre>
	 */
	protected void sequence_Constant(ISerializationContext context, Constant semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CONSTANT__CONST_DECLARATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CONSTANT__CONST_DECLARATION));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.CONSTANT__CONST_ASSIGNMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.CONSTANT__CONST_ASSIGNMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstantAccess().getConstDeclarationConstantDeclarationParserRuleCall_0_0(), semanticObject.getConstDeclaration());
		feeder.accept(grammarAccess.getConstantAccess().getConstAssignmentConstantAssignmentParserRuleCall_2_0(), semanticObject.getConstAssignment());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns CosUnaireList
	 *     OperationUnaire returns CosUnaireList
	 *     CosUnaire returns CosUnaireList
	 *     CosUnaireList returns CosUnaireList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_CosUnaireList(ISerializationContext context, CosUnaireList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_LIST__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCosUnaireListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getCosUnaireListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getCosUnaireListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getCosUnaireListAccess().getListNameRightIDTerminalRuleCall_6_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns CosUnaireNumber
	 *     OperationUnaire returns CosUnaireNumber
	 *     CosUnaire returns CosUnaireNumber
	 *     CosUnaireNumber returns CosUnaireNumber
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID varNameRight=ID)
	 * </pre>
	 */
	protected void sequence_CosUnaireNumber(ISerializationContext context, CosUnaireNumber semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_NUMBER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_NUMBER__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_NUMBER__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_NUMBER__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_NUMBER__VAR_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.COS_UNAIRE_NUMBER__VAR_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCosUnaireNumberAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getCosUnaireNumberAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getCosUnaireNumberAccess().getVarNameRightIDTerminalRuleCall_4_0(), semanticObject.getVarNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns DivisionBinaireListList
	 *     OperationBinaire returns DivisionBinaireListList
	 *     DivisionBinaire returns DivisionBinaireListList
	 *     DivisionBinaireListList returns DivisionBinaireListList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID listNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_DivisionBinaireListList(ISerializationContext context, DivisionBinaireListList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDivisionBinaireListListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getDivisionBinaireListListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getDivisionBinaireListListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getDivisionBinaireListListAccess().getListNameRightIDTerminalRuleCall_9_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getDivisionBinaireListListAccess().getListNameRight2IDTerminalRuleCall_11_0(), semanticObject.getListNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns DivisionBinaireListVal
	 *     OperationBinaire returns DivisionBinaireListVal
	 *     DivisionBinaire returns DivisionBinaireListVal
	 *     DivisionBinaireListVal returns DivisionBinaireListVal
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID valNameRight=ID)
	 * </pre>
	 */
	protected void sequence_DivisionBinaireListVal(ISerializationContext context, DivisionBinaireListVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__VAL_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL__VAL_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDivisionBinaireListValAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getDivisionBinaireListValAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getDivisionBinaireListValAccess().getTypeListRightTypeListNumberParserRuleCall_3_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getDivisionBinaireListValAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getDivisionBinaireListValAccess().getValNameRightIDTerminalRuleCall_6_0(), semanticObject.getValNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns DivisionBinaireValList
	 *     OperationBinaire returns DivisionBinaireValList
	 *     DivisionBinaire returns DivisionBinaireValList
	 *     DivisionBinaireValList returns DivisionBinaireValList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID valNameRight=ID)
	 * </pre>
	 */
	protected void sequence_DivisionBinaireValList(ISerializationContext context, DivisionBinaireValList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__VAL_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_LIST__VAL_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDivisionBinaireValListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getDivisionBinaireValListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getDivisionBinaireValListAccess().getTypeListRightTypeListNumberParserRuleCall_3_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getDivisionBinaireValListAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getDivisionBinaireValListAccess().getValNameRightIDTerminalRuleCall_6_0(), semanticObject.getValNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns DivisionBinaireValVal
	 *     OperationBinaire returns DivisionBinaireValVal
	 *     DivisionBinaire returns DivisionBinaireValVal
	 *     DivisionBinaireValVal returns DivisionBinaireValVal
	 *
	 * Constraint:
	 *     (typeVarLeft=TypeNumber varNameLeft=ID varNameRight1=ID varNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_DivisionBinaireValVal(ISerializationContext context, DivisionBinaireValVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__TYPE_VAR_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__TYPE_VAR_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.DIVISION_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDivisionBinaireValValAccess().getTypeVarLeftTypeNumberParserRuleCall_0_0(), semanticObject.getTypeVarLeft());
		feeder.accept(grammarAccess.getDivisionBinaireValValAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getDivisionBinaireValValAccess().getVarNameRight1IDTerminalRuleCall_3_0(), semanticObject.getVarNameRight1());
		feeder.accept(grammarAccess.getDivisionBinaireValValAccess().getVarNameRight2IDTerminalRuleCall_5_0(), semanticObject.getVarNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns ExpUnaireList
	 *     OperationUnaire returns ExpUnaireList
	 *     ExpUnaire returns ExpUnaireList
	 *     ExpUnaireList returns ExpUnaireList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_ExpUnaireList(ISerializationContext context, ExpUnaireList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_LIST__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExpUnaireListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getExpUnaireListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getExpUnaireListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getExpUnaireListAccess().getListNameRightIDTerminalRuleCall_6_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns ExpUnaireNumber
	 *     OperationUnaire returns ExpUnaireNumber
	 *     ExpUnaire returns ExpUnaireNumber
	 *     ExpUnaireNumber returns ExpUnaireNumber
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID varNameRight=ID)
	 * </pre>
	 */
	protected void sequence_ExpUnaireNumber(ISerializationContext context, ExpUnaireNumber semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_NUMBER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_NUMBER__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_NUMBER__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_NUMBER__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_NUMBER__VAR_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.EXP_UNAIRE_NUMBER__VAR_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExpUnaireNumberAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getExpUnaireNumberAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getExpUnaireNumberAccess().getVarNameRightIDTerminalRuleCall_4_0(), semanticObject.getVarNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MaxBinaireListList
	 *     OperationBinaire returns MaxBinaireListList
	 *     MaxBinaire returns MaxBinaireListList
	 *     MaxBinaireListList returns MaxBinaireListList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID listNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_MaxBinaireListList(ISerializationContext context, MaxBinaireListList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMaxBinaireListListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getMaxBinaireListListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getMaxBinaireListListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getMaxBinaireListListAccess().getListNameRightIDTerminalRuleCall_9_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getMaxBinaireListListAccess().getListNameRight2IDTerminalRuleCall_11_0(), semanticObject.getListNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MaxBinaireListVal
	 *     OperationBinaire returns MaxBinaireListVal
	 *     MaxBinaire returns MaxBinaireListVal
	 *     MaxBinaireListVal returns MaxBinaireListVal
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID valNameRight=ID)
	 * </pre>
	 */
	protected void sequence_MaxBinaireListVal(ISerializationContext context, MaxBinaireListVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__VAL_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_LIST_VAL__VAL_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMaxBinaireListValAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getMaxBinaireListValAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getMaxBinaireListValAccess().getTypeListRightTypeListNumberParserRuleCall_3_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getMaxBinaireListValAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getMaxBinaireListValAccess().getValNameRightIDTerminalRuleCall_6_0(), semanticObject.getValNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MaxBinaireValVal
	 *     OperationBinaire returns MaxBinaireValVal
	 *     MaxBinaire returns MaxBinaireValVal
	 *     MaxBinaireValVal returns MaxBinaireValVal
	 *
	 * Constraint:
	 *     (typeVarLeft=TypeNumber varNameLeft=ID varNameRight1=ID varNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_MaxBinaireValVal(ISerializationContext context, MaxBinaireValVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__TYPE_VAR_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__TYPE_VAR_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMaxBinaireValValAccess().getTypeVarLeftTypeNumberParserRuleCall_0_0(), semanticObject.getTypeVarLeft());
		feeder.accept(grammarAccess.getMaxBinaireValValAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getMaxBinaireValValAccess().getVarNameRight1IDTerminalRuleCall_4_0(), semanticObject.getVarNameRight1());
		feeder.accept(grammarAccess.getMaxBinaireValValAccess().getVarNameRight2IDTerminalRuleCall_6_0(), semanticObject.getVarNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MaxUnaire
	 *     OperationUnaire returns MaxUnaire
	 *     MaxUnaire returns MaxUnaire
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_MaxUnaire(ISerializationContext context, MaxUnaire semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_UNAIRE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_UNAIRE__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_UNAIRE__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_UNAIRE__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MAX_UNAIRE__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MAX_UNAIRE__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMaxUnaireAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getMaxUnaireAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getMaxUnaireAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Methode returns Methode
	 *
	 * Constraint:
	 *     (
	 *         type=Type 
	 *         (parameter=Parameter parameters+=Parameter*)? 
	 *         listName=ID 
	 *         constants+=Constant* 
	 *         operations+=Operation* 
	 *         return=Return
	 *     )
	 * </pre>
	 */
	protected void sequence_Methode(ISerializationContext context, Methode semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MinBinaireListList
	 *     OperationBinaire returns MinBinaireListList
	 *     MinBinaire returns MinBinaireListList
	 *     MinBinaireListList returns MinBinaireListList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID listNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_MinBinaireListList(ISerializationContext context, MinBinaireListList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMinBinaireListListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getMinBinaireListListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getMinBinaireListListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getMinBinaireListListAccess().getListNameRightIDTerminalRuleCall_9_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getMinBinaireListListAccess().getListNameRight2IDTerminalRuleCall_11_0(), semanticObject.getListNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MinBinaireListVal
	 *     OperationBinaire returns MinBinaireListVal
	 *     MinBinaire returns MinBinaireListVal
	 *     MinBinaireListVal returns MinBinaireListVal
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID valNameRight=ID)
	 * </pre>
	 */
	protected void sequence_MinBinaireListVal(ISerializationContext context, MinBinaireListVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__VAL_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_LIST_VAL__VAL_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMinBinaireListValAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getMinBinaireListValAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getMinBinaireListValAccess().getTypeListRightTypeListNumberParserRuleCall_3_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getMinBinaireListValAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getMinBinaireListValAccess().getValNameRightIDTerminalRuleCall_6_0(), semanticObject.getValNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MinBinaireValVal
	 *     OperationBinaire returns MinBinaireValVal
	 *     MinBinaire returns MinBinaireValVal
	 *     MinBinaireValVal returns MinBinaireValVal
	 *
	 * Constraint:
	 *     (typeVarLeft=TypeNumber varNameLeft=ID varNameRight1=ID varNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_MinBinaireValVal(ISerializationContext context, MinBinaireValVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__TYPE_VAR_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__TYPE_VAR_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMinBinaireValValAccess().getTypeVarLeftTypeNumberParserRuleCall_0_0(), semanticObject.getTypeVarLeft());
		feeder.accept(grammarAccess.getMinBinaireValValAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getMinBinaireValValAccess().getVarNameRight1IDTerminalRuleCall_4_0(), semanticObject.getVarNameRight1());
		feeder.accept(grammarAccess.getMinBinaireValValAccess().getVarNameRight2IDTerminalRuleCall_6_0(), semanticObject.getVarNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns MinUnaire
	 *     OperationUnaire returns MinUnaire
	 *     MinUnaire returns MinUnaire
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_MinUnaire(ISerializationContext context, MinUnaire semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_UNAIRE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_UNAIRE__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_UNAIRE__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_UNAIRE__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.MIN_UNAIRE__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.MIN_UNAIRE__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMinUnaireAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getMinUnaireAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getMinUnaireAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns OppositeUnaireList
	 *     OperationUnaire returns OppositeUnaireList
	 *     OppositeUnaire returns OppositeUnaireList
	 *     OppositeUnaireList returns OppositeUnaireList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_OppositeUnaireList(ISerializationContext context, OppositeUnaireList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_LIST__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOppositeUnaireListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getOppositeUnaireListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getOppositeUnaireListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getOppositeUnaireListAccess().getListNameRightIDTerminalRuleCall_6_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns OppositeUnaireNumber
	 *     OperationUnaire returns OppositeUnaireNumber
	 *     OppositeUnaire returns OppositeUnaireNumber
	 *     OppositeUnaireNumber returns OppositeUnaireNumber
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID varNameRight=ID)
	 * </pre>
	 */
	protected void sequence_OppositeUnaireNumber(ISerializationContext context, OppositeUnaireNumber semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_NUMBER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_NUMBER__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_NUMBER__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_NUMBER__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_NUMBER__VAR_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.OPPOSITE_UNAIRE_NUMBER__VAR_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOppositeUnaireNumberAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getOppositeUnaireNumberAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getOppositeUnaireNumberAccess().getVarNameRightIDTerminalRuleCall_4_0(), semanticObject.getVarNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Parameter returns Parameter
	 *
	 * Constraint:
	 *     (type=Type varName=ID)
	 * </pre>
	 */
	protected void sequence_Parameter(ISerializationContext context, projetIDM.javaSFT.Parameter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PARAMETER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PARAMETER__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PARAMETER__VAR_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PARAMETER__VAR_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParameterAccess().getTypeTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getParameterAccess().getVarNameIDTerminalRuleCall_4_0(), semanticObject.getVarName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns ProductBinaireListList
	 *     OperationBinaire returns ProductBinaireListList
	 *     ProductBinaire returns ProductBinaireListList
	 *     ProductBinaireListList returns ProductBinaireListList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID listNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_ProductBinaireListList(ISerializationContext context, ProductBinaireListList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProductBinaireListListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getProductBinaireListListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getProductBinaireListListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getProductBinaireListListAccess().getListNameRightIDTerminalRuleCall_9_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getProductBinaireListListAccess().getListNameRight2IDTerminalRuleCall_11_0(), semanticObject.getListNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns ProductBinaireListVal
	 *     OperationBinaire returns ProductBinaireListVal
	 *     ProductBinaire returns ProductBinaireListVal
	 *     ProductBinaireListVal returns ProductBinaireListVal
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID valNameRight=ID)
	 * </pre>
	 */
	protected void sequence_ProductBinaireListVal(ISerializationContext context, ProductBinaireListVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__VAL_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_LIST_VAL__VAL_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProductBinaireListValAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getProductBinaireListValAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getProductBinaireListValAccess().getTypeListRightTypeListNumberParserRuleCall_3_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getProductBinaireListValAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getProductBinaireListValAccess().getValNameRightIDTerminalRuleCall_6_0(), semanticObject.getValNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns ProductBinaireValVal
	 *     OperationBinaire returns ProductBinaireValVal
	 *     ProductBinaire returns ProductBinaireValVal
	 *     ProductBinaireValVal returns ProductBinaireValVal
	 *
	 * Constraint:
	 *     (typeVarLeft=TypeNumber varNameLeft=ID varNameRight1=ID varNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_ProductBinaireValVal(ISerializationContext context, ProductBinaireValVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__TYPE_VAR_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__TYPE_VAR_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProductBinaireValValAccess().getTypeVarLeftTypeNumberParserRuleCall_0_0(), semanticObject.getTypeVarLeft());
		feeder.accept(grammarAccess.getProductBinaireValValAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getProductBinaireValValAccess().getVarNameRight1IDTerminalRuleCall_3_0(), semanticObject.getVarNameRight1());
		feeder.accept(grammarAccess.getProductBinaireValValAccess().getVarNameRight2IDTerminalRuleCall_5_0(), semanticObject.getVarNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns ProductUnaire
	 *     OperationUnaire returns ProductUnaire
	 *     ProductUnaire returns ProductUnaire
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_ProductUnaire(ISerializationContext context, ProductUnaire semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_UNAIRE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_UNAIRE__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_UNAIRE__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_UNAIRE__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.PRODUCT_UNAIRE__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.PRODUCT_UNAIRE__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProductUnaireAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getProductUnaireAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getProductUnaireAccess().getListNameRightIDTerminalRuleCall_3_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Return returns Return
	 *
	 * Constraint:
	 *     varName=ID
	 * </pre>
	 */
	protected void sequence_Return(ISerializationContext context, Return semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.RETURN__VAR_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.RETURN__VAR_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getReturnAccess().getVarNameIDTerminalRuleCall_1_0(), semanticObject.getVarName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SinUnaireList
	 *     OperationUnaire returns SinUnaireList
	 *     SinUnaire returns SinUnaireList
	 *     SinUnaireList returns SinUnaireList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_SinUnaireList(ISerializationContext context, SinUnaireList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_LIST__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSinUnaireListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getSinUnaireListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getSinUnaireListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getSinUnaireListAccess().getListNameRightIDTerminalRuleCall_6_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SinUnaireNumber
	 *     OperationUnaire returns SinUnaireNumber
	 *     SinUnaire returns SinUnaireNumber
	 *     SinUnaireNumber returns SinUnaireNumber
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID varNameRight=ID)
	 * </pre>
	 */
	protected void sequence_SinUnaireNumber(ISerializationContext context, SinUnaireNumber semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_NUMBER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_NUMBER__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_NUMBER__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_NUMBER__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_NUMBER__VAR_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SIN_UNAIRE_NUMBER__VAR_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSinUnaireNumberAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getSinUnaireNumberAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getSinUnaireNumberAccess().getVarNameRightIDTerminalRuleCall_4_0(), semanticObject.getVarNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SqrtUnaireList
	 *     OperationUnaire returns SqrtUnaireList
	 *     SqrtUnaire returns SqrtUnaireList
	 *     SqrtUnaireList returns SqrtUnaireList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeListNumber listNameLeft=ID typeListRight=TypeListNumber listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_SqrtUnaireList(ISerializationContext context, SqrtUnaireList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_LIST__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSqrtUnaireListAccess().getTypeListLeftTypeListNumberParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getSqrtUnaireListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getSqrtUnaireListAccess().getTypeListRightTypeListNumberParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getSqrtUnaireListAccess().getListNameRightIDTerminalRuleCall_6_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SqrtUnaireNumber
	 *     OperationUnaire returns SqrtUnaireNumber
	 *     SqrtUnaire returns SqrtUnaireNumber
	 *     SqrtUnaireNumber returns SqrtUnaireNumber
	 *
	 * Constraint:
	 *     (type=TypeNumber varNameLeft=ID varNameRight=ID)
	 * </pre>
	 */
	protected void sequence_SqrtUnaireNumber(ISerializationContext context, SqrtUnaireNumber semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_NUMBER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_NUMBER__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_NUMBER__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_NUMBER__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_NUMBER__VAR_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SQRT_UNAIRE_NUMBER__VAR_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSqrtUnaireNumberAccess().getTypeTypeNumberParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getSqrtUnaireNumberAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getSqrtUnaireNumberAccess().getVarNameRightIDTerminalRuleCall_4_0(), semanticObject.getVarNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SumBinaireListList
	 *     OperationBinaire returns SumBinaireListList
	 *     SumBinaire returns SumBinaireListList
	 *     SumBinaireListList returns SumBinaireListList
	 *
	 * Constraint:
	 *     (typeListLeft=TypeList listNameLeft=ID typeListRight=TypeList listNameRight=ID listNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_SumBinaireListList(ISerializationContext context, SumBinaireListList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_LIST__LIST_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSumBinaireListListAccess().getTypeListLeftTypeListParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getSumBinaireListListAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getSumBinaireListListAccess().getTypeListRightTypeListParserRuleCall_4_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getSumBinaireListListAccess().getListNameRightIDTerminalRuleCall_9_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getSumBinaireListListAccess().getListNameRight2IDTerminalRuleCall_11_0(), semanticObject.getListNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SumBinaireListVal
	 *     OperationBinaire returns SumBinaireListVal
	 *     SumBinaire returns SumBinaireListVal
	 *     SumBinaireListVal returns SumBinaireListVal
	 *
	 * Constraint:
	 *     (typeListLeft=TypeList listNameLeft=ID typeListRight=TypeList listNameRight=ID valNameRight=ID)
	 * </pre>
	 */
	protected void sequence_SumBinaireListVal(ISerializationContext context, SumBinaireListVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__TYPE_LIST_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__TYPE_LIST_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__LIST_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__LIST_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__LIST_NAME_RIGHT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__VAL_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_LIST_VAL__VAL_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSumBinaireListValAccess().getTypeListLeftTypeListParserRuleCall_0_0(), semanticObject.getTypeListLeft());
		feeder.accept(grammarAccess.getSumBinaireListValAccess().getListNameLeftIDTerminalRuleCall_1_0(), semanticObject.getListNameLeft());
		feeder.accept(grammarAccess.getSumBinaireListValAccess().getTypeListRightTypeListParserRuleCall_3_0(), semanticObject.getTypeListRight());
		feeder.accept(grammarAccess.getSumBinaireListValAccess().getListNameRightIDTerminalRuleCall_4_0(), semanticObject.getListNameRight());
		feeder.accept(grammarAccess.getSumBinaireListValAccess().getValNameRightIDTerminalRuleCall_6_0(), semanticObject.getValNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SumBinaireValVal
	 *     OperationBinaire returns SumBinaireValVal
	 *     SumBinaire returns SumBinaireValVal
	 *     SumBinaireValVal returns SumBinaireValVal
	 *
	 * Constraint:
	 *     (typeVarLeft=Type varNameLeft=ID varNameRight1=ID varNameRight2=ID)
	 * </pre>
	 */
	protected void sequence_SumBinaireValVal(ISerializationContext context, SumBinaireValVal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__TYPE_VAR_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__TYPE_VAR_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSumBinaireValValAccess().getTypeVarLeftTypeParserRuleCall_0_0(), semanticObject.getTypeVarLeft());
		feeder.accept(grammarAccess.getSumBinaireValValAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getSumBinaireValValAccess().getVarNameRight1IDTerminalRuleCall_3_0(), semanticObject.getVarNameRight1());
		feeder.accept(grammarAccess.getSumBinaireValValAccess().getVarNameRight2IDTerminalRuleCall_5_0(), semanticObject.getVarNameRight2());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Operation returns SumUnaire
	 *     OperationUnaire returns SumUnaire
	 *     SumUnaire returns SumUnaire
	 *
	 * Constraint:
	 *     (type=Type varNameLeft=ID listNameRight=ID)
	 * </pre>
	 */
	protected void sequence_SumUnaire(ISerializationContext context, SumUnaire semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_UNAIRE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_UNAIRE__TYPE));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_UNAIRE__VAR_NAME_LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_UNAIRE__VAR_NAME_LEFT));
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.SUM_UNAIRE__LIST_NAME_RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.SUM_UNAIRE__LIST_NAME_RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSumUnaireAccess().getTypeTypeParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getSumUnaireAccess().getVarNameLeftIDTerminalRuleCall_1_0(), semanticObject.getVarNameLeft());
		feeder.accept(grammarAccess.getSumUnaireAccess().getListNameRightIDTerminalRuleCall_3_0(), semanticObject.getListNameRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeListNumber returns TypeListNumber
	 *
	 * Constraint:
	 *     type=TypeNumber
	 * </pre>
	 */
	protected void sequence_TypeListNumber(ISerializationContext context, TypeListNumber semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.TYPE_LIST_NUMBER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.TYPE_LIST_NUMBER__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypeListNumberAccess().getTypeTypeNumberParserRuleCall_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeList returns TypeList
	 *
	 * Constraint:
	 *     type=Type
	 * </pre>
	 */
	protected void sequence_TypeList(ISerializationContext context, TypeList semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JavaSFTPackage.Literals.TYPE_LIST__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JavaSFTPackage.Literals.TYPE_LIST__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypeListAccess().getTypeTypeParserRuleCall_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
}
