/*
 * generated by Xtext 2.37.0
 */
package projetIDM.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import projetIDM.services.JavaSFTGrammarAccess;

@SuppressWarnings("all")
public class JavaSFTSyntacticSequencer extends AbstractSyntacticSequencer {

	protected JavaSFTGrammarAccess grammarAccess;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (JavaSFTGrammarAccess) access;
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getImportRule())
			return getImportToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSIZEVARRule())
			return getSIZEVARToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSPACERule())
			return getSPACEToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getTypeRule())
			return getTypeToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Import: "import" "java.util.ArrayList;"
	 * 		"import" "java.util.List;"
	 * 		"import" "java.util.Collections;"
	 * 		"import" "java.util.stream.Collectors;"
	 * 		"import" "java.util.stream.IntStream;";
	 */
	protected String getImportToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "import java.util.ArrayList; import java.util.List; import java.util.Collections; import java.util.stream.Collectors; import java.util.stream.IntStream;";
	}
	
	/**
	 * terminal SIZEVAR: "size";
	 */
	protected String getSIZEVARToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "size";
	}
	
	/**
	 * terminal SPACE: ' ';
	 */
	protected String getSPACEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return " ";
	}
	
	/**
	 * Type: TypeNumber | TYPE_STRING ;
	 */
	protected String getTypeToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "Integer";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

}
