/*
 * generated by Xtext 2.37.0
 */
package projetIDM.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import projetIDM.javaScriptForTable.ui.internal.JavaScriptForTableActivator;

public class JavaSFTUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JavaScriptForTableActivator.getInstance().getInjector("projetIDM.JavaSFT");
	}

}
