/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.Class#getClassName <em>Class Name</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Class#getMethode <em>Methode</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getClass_()
 * @model
 * @generated
 */
public interface Class extends JavaSFT
{
  /**
   * Returns the value of the '<em><b>Class Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Name</em>' containment reference.
   * @see #setClassName(ClassName)
   * @see projetIDM.javaSFT.JavaSFTPackage#getClass_ClassName()
   * @model containment="true"
   * @generated
   */
  ClassName getClassName();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Class#getClassName <em>Class Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Name</em>' containment reference.
   * @see #getClassName()
   * @generated
   */
  void setClassName(ClassName value);

  /**
   * Returns the value of the '<em><b>Methode</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methode</em>' containment reference.
   * @see #setMethode(Methode)
   * @see projetIDM.javaSFT.JavaSFTPackage#getClass_Methode()
   * @model containment="true"
   * @generated
   */
  Methode getMethode();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Class#getMethode <em>Methode</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Methode</em>' containment reference.
   * @see #getMethode()
   * @generated
   */
  void setMethode(Methode value);

} // Class
