/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constant Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.ConstantAssignment#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getConstantAssignment()
 * @model
 * @generated
 */
public interface ConstantAssignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getConstantAssignment_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.ConstantAssignment#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // ConstantAssignment
