/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.Constant#getConstDeclaration <em>Const Declaration</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Constant#getConstAssignment <em>Const Assignment</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getConstant()
 * @model
 * @generated
 */
public interface Constant extends EObject
{
  /**
   * Returns the value of the '<em><b>Const Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Declaration</em>' containment reference.
   * @see #setConstDeclaration(ConstantDeclaration)
   * @see projetIDM.javaSFT.JavaSFTPackage#getConstant_ConstDeclaration()
   * @model containment="true"
   * @generated
   */
  ConstantDeclaration getConstDeclaration();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Constant#getConstDeclaration <em>Const Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Declaration</em>' containment reference.
   * @see #getConstDeclaration()
   * @generated
   */
  void setConstDeclaration(ConstantDeclaration value);

  /**
   * Returns the value of the '<em><b>Const Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Assignment</em>' containment reference.
   * @see #setConstAssignment(ConstantAssignment)
   * @see projetIDM.javaSFT.JavaSFTPackage#getConstant_ConstAssignment()
   * @model containment="true"
   * @generated
   */
  ConstantAssignment getConstAssignment();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Constant#getConstAssignment <em>Const Assignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Assignment</em>' containment reference.
   * @see #getConstAssignment()
   * @generated
   */
  void setConstAssignment(ConstantAssignment value);

} // Constant
