/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Division Binaire Val Val</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.DivisionBinaireValVal#getTypeVarLeft <em>Type Var Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.DivisionBinaireValVal#getVarNameLeft <em>Var Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.DivisionBinaireValVal#getVarNameRight1 <em>Var Name Right1</em>}</li>
 *   <li>{@link projetIDM.javaSFT.DivisionBinaireValVal#getVarNameRight2 <em>Var Name Right2</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getDivisionBinaireValVal()
 * @model
 * @generated
 */
public interface DivisionBinaireValVal extends DivisionBinaire
{
  /**
   * Returns the value of the '<em><b>Type Var Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Var Left</em>' attribute.
   * @see #setTypeVarLeft(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getDivisionBinaireValVal_TypeVarLeft()
   * @model
   * @generated
   */
  String getTypeVarLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.DivisionBinaireValVal#getTypeVarLeft <em>Type Var Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Var Left</em>' attribute.
   * @see #getTypeVarLeft()
   * @generated
   */
  void setTypeVarLeft(String value);

  /**
   * Returns the value of the '<em><b>Var Name Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name Left</em>' attribute.
   * @see #setVarNameLeft(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getDivisionBinaireValVal_VarNameLeft()
   * @model
   * @generated
   */
  String getVarNameLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.DivisionBinaireValVal#getVarNameLeft <em>Var Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name Left</em>' attribute.
   * @see #getVarNameLeft()
   * @generated
   */
  void setVarNameLeft(String value);

  /**
   * Returns the value of the '<em><b>Var Name Right1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name Right1</em>' attribute.
   * @see #setVarNameRight1(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getDivisionBinaireValVal_VarNameRight1()
   * @model
   * @generated
   */
  String getVarNameRight1();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.DivisionBinaireValVal#getVarNameRight1 <em>Var Name Right1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name Right1</em>' attribute.
   * @see #getVarNameRight1()
   * @generated
   */
  void setVarNameRight1(String value);

  /**
   * Returns the value of the '<em><b>Var Name Right2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name Right2</em>' attribute.
   * @see #setVarNameRight2(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getDivisionBinaireValVal_VarNameRight2()
   * @model
   * @generated
   */
  String getVarNameRight2();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.DivisionBinaireValVal#getVarNameRight2 <em>Var Name Right2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name Right2</em>' attribute.
   * @see #getVarNameRight2()
   * @generated
   */
  void setVarNameRight2(String value);

} // DivisionBinaireValVal
