/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Unaire Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.ExpUnaireNumber#getType <em>Type</em>}</li>
 *   <li>{@link projetIDM.javaSFT.ExpUnaireNumber#getVarNameLeft <em>Var Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.ExpUnaireNumber#getVarNameRight <em>Var Name Right</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getExpUnaireNumber()
 * @model
 * @generated
 */
public interface ExpUnaireNumber extends ExpUnaire
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getExpUnaireNumber_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.ExpUnaireNumber#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Var Name Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name Left</em>' attribute.
   * @see #setVarNameLeft(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getExpUnaireNumber_VarNameLeft()
   * @model
   * @generated
   */
  String getVarNameLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.ExpUnaireNumber#getVarNameLeft <em>Var Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name Left</em>' attribute.
   * @see #getVarNameLeft()
   * @generated
   */
  void setVarNameLeft(String value);

  /**
   * Returns the value of the '<em><b>Var Name Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name Right</em>' attribute.
   * @see #setVarNameRight(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getExpUnaireNumber_VarNameRight()
   * @model
   * @generated
   */
  String getVarNameRight();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.ExpUnaireNumber#getVarNameRight <em>Var Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name Right</em>' attribute.
   * @see #getVarNameRight()
   * @generated
   */
  void setVarNameRight(String value);

} // ExpUnaireNumber
