/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Java SFT</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getJavaSFT()
 * @model
 * @generated
 */
public interface JavaSFT extends EObject
{
} // JavaSFT
