/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Methode</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.Methode#getType <em>Type</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Methode#getParameter <em>Parameter</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Methode#getParameters <em>Parameters</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Methode#getListName <em>List Name</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Methode#getConstants <em>Constants</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Methode#getOperations <em>Operations</em>}</li>
 *   <li>{@link projetIDM.javaSFT.Methode#getReturn <em>Return</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getMethode()
 * @model
 * @generated
 */
public interface Methode extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMethode_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Methode#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter</em>' containment reference.
   * @see #setParameter(Parameter)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMethode_Parameter()
   * @model containment="true"
   * @generated
   */
  Parameter getParameter();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Methode#getParameter <em>Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter</em>' containment reference.
   * @see #getParameter()
   * @generated
   */
  void setParameter(Parameter value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link projetIDM.javaSFT.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see projetIDM.javaSFT.JavaSFTPackage#getMethode_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>List Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Name</em>' attribute.
   * @see #setListName(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMethode_ListName()
   * @model
   * @generated
   */
  String getListName();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Methode#getListName <em>List Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Name</em>' attribute.
   * @see #getListName()
   * @generated
   */
  void setListName(String value);

  /**
   * Returns the value of the '<em><b>Constants</b></em>' containment reference list.
   * The list contents are of type {@link projetIDM.javaSFT.Constant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constants</em>' containment reference list.
   * @see projetIDM.javaSFT.JavaSFTPackage#getMethode_Constants()
   * @model containment="true"
   * @generated
   */
  EList<Constant> getConstants();

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link projetIDM.javaSFT.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see projetIDM.javaSFT.JavaSFTPackage#getMethode_Operations()
   * @model containment="true"
   * @generated
   */
  EList<Operation> getOperations();

  /**
   * Returns the value of the '<em><b>Return</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return</em>' containment reference.
   * @see #setReturn(Return)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMethode_Return()
   * @model containment="true"
   * @generated
   */
  Return getReturn();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.Methode#getReturn <em>Return</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return</em>' containment reference.
   * @see #getReturn()
   * @generated
   */
  void setReturn(Return value);

} // Methode
