/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Min Binaire List Val</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.MinBinaireListVal#getTypeListLeft <em>Type List Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.MinBinaireListVal#getListNameLeft <em>List Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.MinBinaireListVal#getTypeListRight <em>Type List Right</em>}</li>
 *   <li>{@link projetIDM.javaSFT.MinBinaireListVal#getListNameRight <em>List Name Right</em>}</li>
 *   <li>{@link projetIDM.javaSFT.MinBinaireListVal#getValNameRight <em>Val Name Right</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getMinBinaireListVal()
 * @model
 * @generated
 */
public interface MinBinaireListVal extends MinBinaire
{
  /**
   * Returns the value of the '<em><b>Type List Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type List Left</em>' containment reference.
   * @see #setTypeListLeft(TypeListNumber)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMinBinaireListVal_TypeListLeft()
   * @model containment="true"
   * @generated
   */
  TypeListNumber getTypeListLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.MinBinaireListVal#getTypeListLeft <em>Type List Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type List Left</em>' containment reference.
   * @see #getTypeListLeft()
   * @generated
   */
  void setTypeListLeft(TypeListNumber value);

  /**
   * Returns the value of the '<em><b>List Name Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Name Left</em>' attribute.
   * @see #setListNameLeft(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMinBinaireListVal_ListNameLeft()
   * @model
   * @generated
   */
  String getListNameLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.MinBinaireListVal#getListNameLeft <em>List Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Name Left</em>' attribute.
   * @see #getListNameLeft()
   * @generated
   */
  void setListNameLeft(String value);

  /**
   * Returns the value of the '<em><b>Type List Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type List Right</em>' containment reference.
   * @see #setTypeListRight(TypeListNumber)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMinBinaireListVal_TypeListRight()
   * @model containment="true"
   * @generated
   */
  TypeListNumber getTypeListRight();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.MinBinaireListVal#getTypeListRight <em>Type List Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type List Right</em>' containment reference.
   * @see #getTypeListRight()
   * @generated
   */
  void setTypeListRight(TypeListNumber value);

  /**
   * Returns the value of the '<em><b>List Name Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Name Right</em>' attribute.
   * @see #setListNameRight(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMinBinaireListVal_ListNameRight()
   * @model
   * @generated
   */
  String getListNameRight();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.MinBinaireListVal#getListNameRight <em>List Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Name Right</em>' attribute.
   * @see #getListNameRight()
   * @generated
   */
  void setListNameRight(String value);

  /**
   * Returns the value of the '<em><b>Val Name Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val Name Right</em>' attribute.
   * @see #setValNameRight(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getMinBinaireListVal_ValNameRight()
   * @model
   * @generated
   */
  String getValNameRight();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.MinBinaireListVal#getValNameRight <em>Val Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val Name Right</em>' attribute.
   * @see #getValNameRight()
   * @generated
   */
  void setValNameRight(String value);

} // MinBinaireListVal
