/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends EObject
{
} // Operation
