/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getOperationUnaire()
 * @model
 * @generated
 */
public interface OperationUnaire extends Operation
{
} // OperationUnaire
