/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sin Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getSinUnaire()
 * @model
 * @generated
 */
public interface SinUnaire extends OperationUnaire
{
} // SinUnaire
