/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sqrt Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getSqrtUnaire()
 * @model
 * @generated
 */
public interface SqrtUnaire extends OperationUnaire
{
} // SqrtUnaire
