/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum Binaire</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getSumBinaire()
 * @model
 * @generated
 */
public interface SumBinaire extends OperationBinaire
{
} // SumBinaire
