/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum Binaire List List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.SumBinaireListList#getTypeListLeft <em>Type List Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.SumBinaireListList#getListNameLeft <em>List Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.SumBinaireListList#getTypeListRight <em>Type List Right</em>}</li>
 *   <li>{@link projetIDM.javaSFT.SumBinaireListList#getListNameRight <em>List Name Right</em>}</li>
 *   <li>{@link projetIDM.javaSFT.SumBinaireListList#getListNameRight2 <em>List Name Right2</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getSumBinaireListList()
 * @model
 * @generated
 */
public interface SumBinaireListList extends SumBinaire
{
  /**
   * Returns the value of the '<em><b>Type List Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type List Left</em>' containment reference.
   * @see #setTypeListLeft(TypeList)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumBinaireListList_TypeListLeft()
   * @model containment="true"
   * @generated
   */
  TypeList getTypeListLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumBinaireListList#getTypeListLeft <em>Type List Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type List Left</em>' containment reference.
   * @see #getTypeListLeft()
   * @generated
   */
  void setTypeListLeft(TypeList value);

  /**
   * Returns the value of the '<em><b>List Name Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Name Left</em>' attribute.
   * @see #setListNameLeft(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumBinaireListList_ListNameLeft()
   * @model
   * @generated
   */
  String getListNameLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumBinaireListList#getListNameLeft <em>List Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Name Left</em>' attribute.
   * @see #getListNameLeft()
   * @generated
   */
  void setListNameLeft(String value);

  /**
   * Returns the value of the '<em><b>Type List Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type List Right</em>' containment reference.
   * @see #setTypeListRight(TypeList)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumBinaireListList_TypeListRight()
   * @model containment="true"
   * @generated
   */
  TypeList getTypeListRight();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumBinaireListList#getTypeListRight <em>Type List Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type List Right</em>' containment reference.
   * @see #getTypeListRight()
   * @generated
   */
  void setTypeListRight(TypeList value);

  /**
   * Returns the value of the '<em><b>List Name Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Name Right</em>' attribute.
   * @see #setListNameRight(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumBinaireListList_ListNameRight()
   * @model
   * @generated
   */
  String getListNameRight();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumBinaireListList#getListNameRight <em>List Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Name Right</em>' attribute.
   * @see #getListNameRight()
   * @generated
   */
  void setListNameRight(String value);

  /**
   * Returns the value of the '<em><b>List Name Right2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Name Right2</em>' attribute.
   * @see #setListNameRight2(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumBinaireListList_ListNameRight2()
   * @model
   * @generated
   */
  String getListNameRight2();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumBinaireListList#getListNameRight2 <em>List Name Right2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Name Right2</em>' attribute.
   * @see #getListNameRight2()
   * @generated
   */
  void setListNameRight2(String value);

} // SumBinaireListList
