/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.SumUnaire#getType <em>Type</em>}</li>
 *   <li>{@link projetIDM.javaSFT.SumUnaire#getVarNameLeft <em>Var Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.SumUnaire#getListNameRight <em>List Name Right</em>}</li>
 * </ul>
 *
 * @see projetIDM.javaSFT.JavaSFTPackage#getSumUnaire()
 * @model
 * @generated
 */
public interface SumUnaire extends OperationUnaire
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumUnaire_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumUnaire#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Var Name Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name Left</em>' attribute.
   * @see #setVarNameLeft(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumUnaire_VarNameLeft()
   * @model
   * @generated
   */
  String getVarNameLeft();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumUnaire#getVarNameLeft <em>Var Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name Left</em>' attribute.
   * @see #getVarNameLeft()
   * @generated
   */
  void setVarNameLeft(String value);

  /**
   * Returns the value of the '<em><b>List Name Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Name Right</em>' attribute.
   * @see #setListNameRight(String)
   * @see projetIDM.javaSFT.JavaSFTPackage#getSumUnaire_ListNameRight()
   * @model
   * @generated
   */
  String getListNameRight();

  /**
   * Sets the value of the '{@link projetIDM.javaSFT.SumUnaire#getListNameRight <em>List Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Name Right</em>' attribute.
   * @see #getListNameRight()
   * @generated
   */
  void setListNameRight(String value);

} // SumUnaire
