/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import projetIDM.javaSFT.DivisionBinaireListVal;
import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.TypeListNumber;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Division Binaire List Val</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.impl.DivisionBinaireListValImpl#getTypeListLeft <em>Type List Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.DivisionBinaireListValImpl#getListNameLeft <em>List Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.DivisionBinaireListValImpl#getTypeListRight <em>Type List Right</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.DivisionBinaireListValImpl#getListNameRight <em>List Name Right</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.DivisionBinaireListValImpl#getValNameRight <em>Val Name Right</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DivisionBinaireListValImpl extends DivisionBinaireImpl implements DivisionBinaireListVal
{
  /**
   * The cached value of the '{@link #getTypeListLeft() <em>Type List Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeListLeft()
   * @generated
   * @ordered
   */
  protected TypeListNumber typeListLeft;

  /**
   * The default value of the '{@link #getListNameLeft() <em>List Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListNameLeft()
   * @generated
   * @ordered
   */
  protected static final String LIST_NAME_LEFT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getListNameLeft() <em>List Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListNameLeft()
   * @generated
   * @ordered
   */
  protected String listNameLeft = LIST_NAME_LEFT_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypeListRight() <em>Type List Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeListRight()
   * @generated
   * @ordered
   */
  protected TypeListNumber typeListRight;

  /**
   * The default value of the '{@link #getListNameRight() <em>List Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListNameRight()
   * @generated
   * @ordered
   */
  protected static final String LIST_NAME_RIGHT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getListNameRight() <em>List Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListNameRight()
   * @generated
   * @ordered
   */
  protected String listNameRight = LIST_NAME_RIGHT_EDEFAULT;

  /**
   * The default value of the '{@link #getValNameRight() <em>Val Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValNameRight()
   * @generated
   * @ordered
   */
  protected static final String VAL_NAME_RIGHT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValNameRight() <em>Val Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValNameRight()
   * @generated
   * @ordered
   */
  protected String valNameRight = VAL_NAME_RIGHT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DivisionBinaireListValImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.DIVISION_BINAIRE_LIST_VAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeListNumber getTypeListLeft()
  {
    return typeListLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeListLeft(TypeListNumber newTypeListLeft, NotificationChain msgs)
  {
    TypeListNumber oldTypeListLeft = typeListLeft;
    typeListLeft = newTypeListLeft;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT, oldTypeListLeft, newTypeListLeft);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeListLeft(TypeListNumber newTypeListLeft)
  {
    if (newTypeListLeft != typeListLeft)
    {
      NotificationChain msgs = null;
      if (typeListLeft != null)
        msgs = ((InternalEObject)typeListLeft).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT, null, msgs);
      if (newTypeListLeft != null)
        msgs = ((InternalEObject)newTypeListLeft).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT, null, msgs);
      msgs = basicSetTypeListLeft(newTypeListLeft, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT, newTypeListLeft, newTypeListLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getListNameLeft()
  {
    return listNameLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setListNameLeft(String newListNameLeft)
  {
    String oldListNameLeft = listNameLeft;
    listNameLeft = newListNameLeft;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_LEFT, oldListNameLeft, listNameLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeListNumber getTypeListRight()
  {
    return typeListRight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeListRight(TypeListNumber newTypeListRight, NotificationChain msgs)
  {
    TypeListNumber oldTypeListRight = typeListRight;
    typeListRight = newTypeListRight;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT, oldTypeListRight, newTypeListRight);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeListRight(TypeListNumber newTypeListRight)
  {
    if (newTypeListRight != typeListRight)
    {
      NotificationChain msgs = null;
      if (typeListRight != null)
        msgs = ((InternalEObject)typeListRight).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT, null, msgs);
      if (newTypeListRight != null)
        msgs = ((InternalEObject)newTypeListRight).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT, null, msgs);
      msgs = basicSetTypeListRight(newTypeListRight, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT, newTypeListRight, newTypeListRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getListNameRight()
  {
    return listNameRight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setListNameRight(String newListNameRight)
  {
    String oldListNameRight = listNameRight;
    listNameRight = newListNameRight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_RIGHT, oldListNameRight, listNameRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValNameRight()
  {
    return valNameRight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValNameRight(String newValNameRight)
  {
    String oldValNameRight = valNameRight;
    valNameRight = newValNameRight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__VAL_NAME_RIGHT, oldValNameRight, valNameRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT:
        return basicSetTypeListLeft(null, msgs);
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT:
        return basicSetTypeListRight(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT:
        return getTypeListLeft();
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_LEFT:
        return getListNameLeft();
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT:
        return getTypeListRight();
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_RIGHT:
        return getListNameRight();
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__VAL_NAME_RIGHT:
        return getValNameRight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT:
        setTypeListLeft((TypeListNumber)newValue);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_LEFT:
        setListNameLeft((String)newValue);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT:
        setTypeListRight((TypeListNumber)newValue);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_RIGHT:
        setListNameRight((String)newValue);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__VAL_NAME_RIGHT:
        setValNameRight((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT:
        setTypeListLeft((TypeListNumber)null);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_LEFT:
        setListNameLeft(LIST_NAME_LEFT_EDEFAULT);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT:
        setTypeListRight((TypeListNumber)null);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_RIGHT:
        setListNameRight(LIST_NAME_RIGHT_EDEFAULT);
        return;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__VAL_NAME_RIGHT:
        setValNameRight(VAL_NAME_RIGHT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_LEFT:
        return typeListLeft != null;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_LEFT:
        return LIST_NAME_LEFT_EDEFAULT == null ? listNameLeft != null : !LIST_NAME_LEFT_EDEFAULT.equals(listNameLeft);
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__TYPE_LIST_RIGHT:
        return typeListRight != null;
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__LIST_NAME_RIGHT:
        return LIST_NAME_RIGHT_EDEFAULT == null ? listNameRight != null : !LIST_NAME_RIGHT_EDEFAULT.equals(listNameRight);
      case JavaSFTPackage.DIVISION_BINAIRE_LIST_VAL__VAL_NAME_RIGHT:
        return VAL_NAME_RIGHT_EDEFAULT == null ? valNameRight != null : !VAL_NAME_RIGHT_EDEFAULT.equals(valNameRight);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (listNameLeft: ");
    result.append(listNameLeft);
    result.append(", listNameRight: ");
    result.append(listNameRight);
    result.append(", valNameRight: ");
    result.append(valNameRight);
    result.append(')');
    return result.toString();
  }

} //DivisionBinaireListValImpl
