/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.ecore.EClass;

import projetIDM.javaSFT.ExpUnaire;
import projetIDM.javaSFT.JavaSFTPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpUnaireImpl extends OperationUnaireImpl implements ExpUnaire
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpUnaireImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.EXP_UNAIRE;
  }

} //ExpUnaireImpl
