/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import projetIDM.javaSFT.JavaSFT;
import projetIDM.javaSFT.JavaSFTPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Java SFT</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JavaSFTImpl extends MinimalEObjectImpl.Container implements JavaSFT
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JavaSFTImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.JAVA_SFT;
  }

} //JavaSFTImpl
