/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.ecore.EClass;

import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.MaxBinaire;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Max Binaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MaxBinaireImpl extends OperationBinaireImpl implements MaxBinaire
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MaxBinaireImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.MAX_BINAIRE;
  }

} //MaxBinaireImpl
