/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.MaxUnaire;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Max Unaire</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.impl.MaxUnaireImpl#getType <em>Type</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.MaxUnaireImpl#getVarNameLeft <em>Var Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.MaxUnaireImpl#getListNameRight <em>List Name Right</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MaxUnaireImpl extends OperationUnaireImpl implements MaxUnaire
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getVarNameLeft() <em>Var Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameLeft()
   * @generated
   * @ordered
   */
  protected static final String VAR_NAME_LEFT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarNameLeft() <em>Var Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameLeft()
   * @generated
   * @ordered
   */
  protected String varNameLeft = VAR_NAME_LEFT_EDEFAULT;

  /**
   * The default value of the '{@link #getListNameRight() <em>List Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListNameRight()
   * @generated
   * @ordered
   */
  protected static final String LIST_NAME_RIGHT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getListNameRight() <em>List Name Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListNameRight()
   * @generated
   * @ordered
   */
  protected String listNameRight = LIST_NAME_RIGHT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MaxUnaireImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.MAX_UNAIRE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.MAX_UNAIRE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarNameLeft()
  {
    return varNameLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarNameLeft(String newVarNameLeft)
  {
    String oldVarNameLeft = varNameLeft;
    varNameLeft = newVarNameLeft;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.MAX_UNAIRE__VAR_NAME_LEFT, oldVarNameLeft, varNameLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getListNameRight()
  {
    return listNameRight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setListNameRight(String newListNameRight)
  {
    String oldListNameRight = listNameRight;
    listNameRight = newListNameRight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.MAX_UNAIRE__LIST_NAME_RIGHT, oldListNameRight, listNameRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JavaSFTPackage.MAX_UNAIRE__TYPE:
        return getType();
      case JavaSFTPackage.MAX_UNAIRE__VAR_NAME_LEFT:
        return getVarNameLeft();
      case JavaSFTPackage.MAX_UNAIRE__LIST_NAME_RIGHT:
        return getListNameRight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JavaSFTPackage.MAX_UNAIRE__TYPE:
        setType((String)newValue);
        return;
      case JavaSFTPackage.MAX_UNAIRE__VAR_NAME_LEFT:
        setVarNameLeft((String)newValue);
        return;
      case JavaSFTPackage.MAX_UNAIRE__LIST_NAME_RIGHT:
        setListNameRight((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JavaSFTPackage.MAX_UNAIRE__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case JavaSFTPackage.MAX_UNAIRE__VAR_NAME_LEFT:
        setVarNameLeft(VAR_NAME_LEFT_EDEFAULT);
        return;
      case JavaSFTPackage.MAX_UNAIRE__LIST_NAME_RIGHT:
        setListNameRight(LIST_NAME_RIGHT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JavaSFTPackage.MAX_UNAIRE__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case JavaSFTPackage.MAX_UNAIRE__VAR_NAME_LEFT:
        return VAR_NAME_LEFT_EDEFAULT == null ? varNameLeft != null : !VAR_NAME_LEFT_EDEFAULT.equals(varNameLeft);
      case JavaSFTPackage.MAX_UNAIRE__LIST_NAME_RIGHT:
        return LIST_NAME_RIGHT_EDEFAULT == null ? listNameRight != null : !LIST_NAME_RIGHT_EDEFAULT.equals(listNameRight);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", varNameLeft: ");
    result.append(varNameLeft);
    result.append(", listNameRight: ");
    result.append(listNameRight);
    result.append(')');
    return result.toString();
  }

} //MaxUnaireImpl
