/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.ecore.EClass;

import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.MinBinaire;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Min Binaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MinBinaireImpl extends OperationBinaireImpl implements MinBinaire
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MinBinaireImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.MIN_BINAIRE;
  }

} //MinBinaireImpl
