/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.ecore.EClass;

import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.OppositeUnaire;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Opposite Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OppositeUnaireImpl extends OperationUnaireImpl implements OppositeUnaire
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OppositeUnaireImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.OPPOSITE_UNAIRE;
  }

} //OppositeUnaireImpl
