/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.ecore.EClass;

import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.SumBinaire;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sum Binaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SumBinaireImpl extends OperationBinaireImpl implements SumBinaire
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SumBinaireImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.SUM_BINAIRE;
  }

} //SumBinaireImpl
