/**
 * generated by Xtext 2.37.0
 */
package projetIDM.javaSFT.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import projetIDM.javaSFT.JavaSFTPackage;
import projetIDM.javaSFT.SumBinaireValVal;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sum Binaire Val Val</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link projetIDM.javaSFT.impl.SumBinaireValValImpl#getTypeVarLeft <em>Type Var Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.SumBinaireValValImpl#getVarNameLeft <em>Var Name Left</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.SumBinaireValValImpl#getVarNameRight1 <em>Var Name Right1</em>}</li>
 *   <li>{@link projetIDM.javaSFT.impl.SumBinaireValValImpl#getVarNameRight2 <em>Var Name Right2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SumBinaireValValImpl extends SumBinaireImpl implements SumBinaireValVal
{
  /**
   * The default value of the '{@link #getTypeVarLeft() <em>Type Var Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeVarLeft()
   * @generated
   * @ordered
   */
  protected static final String TYPE_VAR_LEFT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTypeVarLeft() <em>Type Var Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeVarLeft()
   * @generated
   * @ordered
   */
  protected String typeVarLeft = TYPE_VAR_LEFT_EDEFAULT;

  /**
   * The default value of the '{@link #getVarNameLeft() <em>Var Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameLeft()
   * @generated
   * @ordered
   */
  protected static final String VAR_NAME_LEFT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarNameLeft() <em>Var Name Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameLeft()
   * @generated
   * @ordered
   */
  protected String varNameLeft = VAR_NAME_LEFT_EDEFAULT;

  /**
   * The default value of the '{@link #getVarNameRight1() <em>Var Name Right1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameRight1()
   * @generated
   * @ordered
   */
  protected static final String VAR_NAME_RIGHT1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarNameRight1() <em>Var Name Right1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameRight1()
   * @generated
   * @ordered
   */
  protected String varNameRight1 = VAR_NAME_RIGHT1_EDEFAULT;

  /**
   * The default value of the '{@link #getVarNameRight2() <em>Var Name Right2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameRight2()
   * @generated
   * @ordered
   */
  protected static final String VAR_NAME_RIGHT2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarNameRight2() <em>Var Name Right2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarNameRight2()
   * @generated
   * @ordered
   */
  protected String varNameRight2 = VAR_NAME_RIGHT2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SumBinaireValValImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaSFTPackage.Literals.SUM_BINAIRE_VAL_VAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTypeVarLeft()
  {
    return typeVarLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeVarLeft(String newTypeVarLeft)
  {
    String oldTypeVarLeft = typeVarLeft;
    typeVarLeft = newTypeVarLeft;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.SUM_BINAIRE_VAL_VAL__TYPE_VAR_LEFT, oldTypeVarLeft, typeVarLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarNameLeft()
  {
    return varNameLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarNameLeft(String newVarNameLeft)
  {
    String oldVarNameLeft = varNameLeft;
    varNameLeft = newVarNameLeft;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_LEFT, oldVarNameLeft, varNameLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarNameRight1()
  {
    return varNameRight1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarNameRight1(String newVarNameRight1)
  {
    String oldVarNameRight1 = varNameRight1;
    varNameRight1 = newVarNameRight1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1, oldVarNameRight1, varNameRight1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarNameRight2()
  {
    return varNameRight2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarNameRight2(String newVarNameRight2)
  {
    String oldVarNameRight2 = varNameRight2;
    varNameRight2 = newVarNameRight2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2, oldVarNameRight2, varNameRight2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__TYPE_VAR_LEFT:
        return getTypeVarLeft();
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_LEFT:
        return getVarNameLeft();
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1:
        return getVarNameRight1();
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2:
        return getVarNameRight2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__TYPE_VAR_LEFT:
        setTypeVarLeft((String)newValue);
        return;
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_LEFT:
        setVarNameLeft((String)newValue);
        return;
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1:
        setVarNameRight1((String)newValue);
        return;
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2:
        setVarNameRight2((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__TYPE_VAR_LEFT:
        setTypeVarLeft(TYPE_VAR_LEFT_EDEFAULT);
        return;
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_LEFT:
        setVarNameLeft(VAR_NAME_LEFT_EDEFAULT);
        return;
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1:
        setVarNameRight1(VAR_NAME_RIGHT1_EDEFAULT);
        return;
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2:
        setVarNameRight2(VAR_NAME_RIGHT2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__TYPE_VAR_LEFT:
        return TYPE_VAR_LEFT_EDEFAULT == null ? typeVarLeft != null : !TYPE_VAR_LEFT_EDEFAULT.equals(typeVarLeft);
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_LEFT:
        return VAR_NAME_LEFT_EDEFAULT == null ? varNameLeft != null : !VAR_NAME_LEFT_EDEFAULT.equals(varNameLeft);
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT1:
        return VAR_NAME_RIGHT1_EDEFAULT == null ? varNameRight1 != null : !VAR_NAME_RIGHT1_EDEFAULT.equals(varNameRight1);
      case JavaSFTPackage.SUM_BINAIRE_VAL_VAL__VAR_NAME_RIGHT2:
        return VAR_NAME_RIGHT2_EDEFAULT == null ? varNameRight2 != null : !VAR_NAME_RIGHT2_EDEFAULT.equals(varNameRight2);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (typeVarLeft: ");
    result.append(typeVarLeft);
    result.append(", varNameLeft: ");
    result.append(varNameLeft);
    result.append(", varNameRight1: ");
    result.append(varNameRight1);
    result.append(", varNameRight2: ");
    result.append(varNameRight2);
    result.append(')');
    return result.toString();
  }

} //SumBinaireValValImpl
