/*
 * generated by Xtext 2.37.0
 */
package projetIDM;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JavaSFTStandaloneSetup extends JavaSFTStandaloneSetupGenerated {

	public static void doSetup() {
		new JavaSFTStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
