/*
 * generated by Xtext 2.37.0
 */
package projetIDM.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import projetIDM.ide.contentassist.antlr.internal.InternalJavaSFTParser;
import projetIDM.services.JavaSFTGrammarAccess;

public class JavaSFTParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(JavaSFTGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, JavaSFTGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getTypeNumberAccess().getAlternatives(), "rule__TypeNumber__Alternatives");
			builder.put(grammarAccess.getMethodeAccess().getAlternatives_6(), "rule__Methode__Alternatives_6");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getOperationUnaireAccess().getAlternatives(), "rule__OperationUnaire__Alternatives");
			builder.put(grammarAccess.getOperationBinaireAccess().getAlternatives(), "rule__OperationBinaire__Alternatives");
			builder.put(grammarAccess.getOppositeUnaireAccess().getAlternatives(), "rule__OppositeUnaire__Alternatives");
			builder.put(grammarAccess.getCosUnaireAccess().getAlternatives(), "rule__CosUnaire__Alternatives");
			builder.put(grammarAccess.getSinUnaireAccess().getAlternatives(), "rule__SinUnaire__Alternatives");
			builder.put(grammarAccess.getSqrtUnaireAccess().getAlternatives(), "rule__SqrtUnaire__Alternatives");
			builder.put(grammarAccess.getExpUnaireAccess().getAlternatives(), "rule__ExpUnaire__Alternatives");
			builder.put(grammarAccess.getSumBinaireAccess().getAlternatives(), "rule__SumBinaire__Alternatives");
			builder.put(grammarAccess.getProductBinaireAccess().getAlternatives(), "rule__ProductBinaire__Alternatives");
			builder.put(grammarAccess.getDivisionBinaireAccess().getAlternatives(), "rule__DivisionBinaire__Alternatives");
			builder.put(grammarAccess.getMinBinaireAccess().getAlternatives(), "rule__MinBinaire__Alternatives");
			builder.put(grammarAccess.getMaxBinaireAccess().getAlternatives(), "rule__MaxBinaire__Alternatives");
			builder.put(grammarAccess.getJavaSFTAccess().getGroup(), "rule__JavaSFT__Group__0");
			builder.put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
			builder.put(grammarAccess.getTypeListAccess().getGroup(), "rule__TypeList__Group__0");
			builder.put(grammarAccess.getTypeListNumberAccess().getGroup(), "rule__TypeListNumber__Group__0");
			builder.put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
			builder.put(grammarAccess.getClassNameAccess().getGroup(), "rule__ClassName__Group__0");
			builder.put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
			builder.put(grammarAccess.getMethodeAccess().getGroup(), "rule__Methode__Group__0");
			builder.put(grammarAccess.getMethodeAccess().getGroup_6_1(), "rule__Methode__Group_6_1__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getReturnAccess().getGroup(), "rule__Return__Group__0");
			builder.put(grammarAccess.getConstantAccess().getGroup(), "rule__Constant__Group__0");
			builder.put(grammarAccess.getConstantDeclarationAccess().getGroup(), "rule__ConstantDeclaration__Group__0");
			builder.put(grammarAccess.getConstantAssignmentAccess().getGroup(), "rule__ConstantAssignment__Group__0");
			builder.put(grammarAccess.getSumUnaireAccess().getGroup(), "rule__SumUnaire__Group__0");
			builder.put(grammarAccess.getProductUnaireAccess().getGroup(), "rule__ProductUnaire__Group__0");
			builder.put(grammarAccess.getMinUnaireAccess().getGroup(), "rule__MinUnaire__Group__0");
			builder.put(grammarAccess.getMaxUnaireAccess().getGroup(), "rule__MaxUnaire__Group__0");
			builder.put(grammarAccess.getOppositeUnaireListAccess().getGroup(), "rule__OppositeUnaireList__Group__0");
			builder.put(grammarAccess.getOppositeUnaireNumberAccess().getGroup(), "rule__OppositeUnaireNumber__Group__0");
			builder.put(grammarAccess.getCosUnaireListAccess().getGroup(), "rule__CosUnaireList__Group__0");
			builder.put(grammarAccess.getCosUnaireNumberAccess().getGroup(), "rule__CosUnaireNumber__Group__0");
			builder.put(grammarAccess.getSinUnaireListAccess().getGroup(), "rule__SinUnaireList__Group__0");
			builder.put(grammarAccess.getSinUnaireNumberAccess().getGroup(), "rule__SinUnaireNumber__Group__0");
			builder.put(grammarAccess.getSqrtUnaireListAccess().getGroup(), "rule__SqrtUnaireList__Group__0");
			builder.put(grammarAccess.getSqrtUnaireNumberAccess().getGroup(), "rule__SqrtUnaireNumber__Group__0");
			builder.put(grammarAccess.getExpUnaireListAccess().getGroup(), "rule__ExpUnaireList__Group__0");
			builder.put(grammarAccess.getExpUnaireNumberAccess().getGroup(), "rule__ExpUnaireNumber__Group__0");
			builder.put(grammarAccess.getSumBinaireListValAccess().getGroup(), "rule__SumBinaireListVal__Group__0");
			builder.put(grammarAccess.getSumBinaireListListAccess().getGroup(), "rule__SumBinaireListList__Group__0");
			builder.put(grammarAccess.getSumBinaireValValAccess().getGroup(), "rule__SumBinaireValVal__Group__0");
			builder.put(grammarAccess.getProductBinaireListValAccess().getGroup(), "rule__ProductBinaireListVal__Group__0");
			builder.put(grammarAccess.getProductBinaireListListAccess().getGroup(), "rule__ProductBinaireListList__Group__0");
			builder.put(grammarAccess.getProductBinaireValValAccess().getGroup(), "rule__ProductBinaireValVal__Group__0");
			builder.put(grammarAccess.getDivisionBinaireListValAccess().getGroup(), "rule__DivisionBinaireListVal__Group__0");
			builder.put(grammarAccess.getDivisionBinaireValListAccess().getGroup(), "rule__DivisionBinaireValList__Group__0");
			builder.put(grammarAccess.getDivisionBinaireListListAccess().getGroup(), "rule__DivisionBinaireListList__Group__0");
			builder.put(grammarAccess.getDivisionBinaireValValAccess().getGroup(), "rule__DivisionBinaireValVal__Group__0");
			builder.put(grammarAccess.getMinBinaireListValAccess().getGroup(), "rule__MinBinaireListVal__Group__0");
			builder.put(grammarAccess.getMinBinaireListListAccess().getGroup(), "rule__MinBinaireListList__Group__0");
			builder.put(grammarAccess.getMinBinaireValValAccess().getGroup(), "rule__MinBinaireValVal__Group__0");
			builder.put(grammarAccess.getMaxBinaireListValAccess().getGroup(), "rule__MaxBinaireListVal__Group__0");
			builder.put(grammarAccess.getMaxBinaireListListAccess().getGroup(), "rule__MaxBinaireListList__Group__0");
			builder.put(grammarAccess.getMaxBinaireValValAccess().getGroup(), "rule__MaxBinaireValVal__Group__0");
			builder.put(grammarAccess.getTypeListAccess().getTypeAssignment_1(), "rule__TypeList__TypeAssignment_1");
			builder.put(grammarAccess.getTypeListNumberAccess().getTypeAssignment_1(), "rule__TypeListNumber__TypeAssignment_1");
			builder.put(grammarAccess.getClassNameAccess().getNameAssignment_0(), "rule__ClassName__NameAssignment_0");
			builder.put(grammarAccess.getClassAccess().getClassNameAssignment_2(), "rule__Class__ClassNameAssignment_2");
			builder.put(grammarAccess.getClassAccess().getMethodeAssignment_4(), "rule__Class__MethodeAssignment_4");
			builder.put(grammarAccess.getMethodeAccess().getTypeAssignment_3(), "rule__Methode__TypeAssignment_3");
			builder.put(grammarAccess.getMethodeAccess().getParameterAssignment_6_1_0(), "rule__Methode__ParameterAssignment_6_1_0");
			builder.put(grammarAccess.getMethodeAccess().getParametersAssignment_6_1_1(), "rule__Methode__ParametersAssignment_6_1_1");
			builder.put(grammarAccess.getMethodeAccess().getListNameAssignment_12(), "rule__Methode__ListNameAssignment_12");
			builder.put(grammarAccess.getMethodeAccess().getConstantsAssignment_14(), "rule__Methode__ConstantsAssignment_14");
			builder.put(grammarAccess.getMethodeAccess().getOperationsAssignment_15(), "rule__Methode__OperationsAssignment_15");
			builder.put(grammarAccess.getMethodeAccess().getReturnAssignment_16(), "rule__Methode__ReturnAssignment_16");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_2(), "rule__Parameter__TypeAssignment_2");
			builder.put(grammarAccess.getParameterAccess().getVarNameAssignment_4(), "rule__Parameter__VarNameAssignment_4");
			builder.put(grammarAccess.getReturnAccess().getVarNameAssignment_1(), "rule__Return__VarNameAssignment_1");
			builder.put(grammarAccess.getConstantAccess().getConstDeclarationAssignment_0(), "rule__Constant__ConstDeclarationAssignment_0");
			builder.put(grammarAccess.getConstantAccess().getConstAssignmentAssignment_2(), "rule__Constant__ConstAssignmentAssignment_2");
			builder.put(grammarAccess.getConstantDeclarationAccess().getTypeAssignment_1(), "rule__ConstantDeclaration__TypeAssignment_1");
			builder.put(grammarAccess.getConstantDeclarationAccess().getVarNameAssignment_2(), "rule__ConstantDeclaration__VarNameAssignment_2");
			builder.put(grammarAccess.getConstantAssignmentAccess().getValueAssignment_2(), "rule__ConstantAssignment__ValueAssignment_2");
			builder.put(grammarAccess.getSumUnaireAccess().getTypeAssignment_0(), "rule__SumUnaire__TypeAssignment_0");
			builder.put(grammarAccess.getSumUnaireAccess().getVarNameLeftAssignment_1(), "rule__SumUnaire__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getSumUnaireAccess().getListNameRightAssignment_3(), "rule__SumUnaire__ListNameRightAssignment_3");
			builder.put(grammarAccess.getProductUnaireAccess().getTypeAssignment_0(), "rule__ProductUnaire__TypeAssignment_0");
			builder.put(grammarAccess.getProductUnaireAccess().getVarNameLeftAssignment_1(), "rule__ProductUnaire__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getProductUnaireAccess().getListNameRightAssignment_3(), "rule__ProductUnaire__ListNameRightAssignment_3");
			builder.put(grammarAccess.getMinUnaireAccess().getTypeAssignment_0(), "rule__MinUnaire__TypeAssignment_0");
			builder.put(grammarAccess.getMinUnaireAccess().getVarNameLeftAssignment_1(), "rule__MinUnaire__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getMinUnaireAccess().getListNameRightAssignment_4(), "rule__MinUnaire__ListNameRightAssignment_4");
			builder.put(grammarAccess.getMaxUnaireAccess().getTypeAssignment_0(), "rule__MaxUnaire__TypeAssignment_0");
			builder.put(grammarAccess.getMaxUnaireAccess().getVarNameLeftAssignment_1(), "rule__MaxUnaire__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getMaxUnaireAccess().getListNameRightAssignment_4(), "rule__MaxUnaire__ListNameRightAssignment_4");
			builder.put(grammarAccess.getOppositeUnaireListAccess().getTypeListLeftAssignment_0(), "rule__OppositeUnaireList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getOppositeUnaireListAccess().getListNameLeftAssignment_1(), "rule__OppositeUnaireList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getOppositeUnaireListAccess().getTypeListRightAssignment_4(), "rule__OppositeUnaireList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getOppositeUnaireListAccess().getListNameRightAssignment_6(), "rule__OppositeUnaireList__ListNameRightAssignment_6");
			builder.put(grammarAccess.getOppositeUnaireNumberAccess().getTypeAssignment_0(), "rule__OppositeUnaireNumber__TypeAssignment_0");
			builder.put(grammarAccess.getOppositeUnaireNumberAccess().getVarNameLeftAssignment_1(), "rule__OppositeUnaireNumber__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getOppositeUnaireNumberAccess().getVarNameRightAssignment_4(), "rule__OppositeUnaireNumber__VarNameRightAssignment_4");
			builder.put(grammarAccess.getCosUnaireListAccess().getTypeListLeftAssignment_0(), "rule__CosUnaireList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getCosUnaireListAccess().getListNameLeftAssignment_1(), "rule__CosUnaireList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getCosUnaireListAccess().getTypeListRightAssignment_4(), "rule__CosUnaireList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getCosUnaireListAccess().getListNameRightAssignment_6(), "rule__CosUnaireList__ListNameRightAssignment_6");
			builder.put(grammarAccess.getCosUnaireNumberAccess().getTypeAssignment_0(), "rule__CosUnaireNumber__TypeAssignment_0");
			builder.put(grammarAccess.getCosUnaireNumberAccess().getVarNameLeftAssignment_1(), "rule__CosUnaireNumber__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getCosUnaireNumberAccess().getVarNameRightAssignment_4(), "rule__CosUnaireNumber__VarNameRightAssignment_4");
			builder.put(grammarAccess.getSinUnaireListAccess().getTypeListLeftAssignment_0(), "rule__SinUnaireList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getSinUnaireListAccess().getListNameLeftAssignment_1(), "rule__SinUnaireList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getSinUnaireListAccess().getTypeListRightAssignment_4(), "rule__SinUnaireList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getSinUnaireListAccess().getListNameRightAssignment_6(), "rule__SinUnaireList__ListNameRightAssignment_6");
			builder.put(grammarAccess.getSinUnaireNumberAccess().getTypeAssignment_0(), "rule__SinUnaireNumber__TypeAssignment_0");
			builder.put(grammarAccess.getSinUnaireNumberAccess().getVarNameLeftAssignment_1(), "rule__SinUnaireNumber__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getSinUnaireNumberAccess().getVarNameRightAssignment_4(), "rule__SinUnaireNumber__VarNameRightAssignment_4");
			builder.put(grammarAccess.getSqrtUnaireListAccess().getTypeListLeftAssignment_0(), "rule__SqrtUnaireList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getSqrtUnaireListAccess().getListNameLeftAssignment_1(), "rule__SqrtUnaireList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getSqrtUnaireListAccess().getTypeListRightAssignment_4(), "rule__SqrtUnaireList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getSqrtUnaireListAccess().getListNameRightAssignment_6(), "rule__SqrtUnaireList__ListNameRightAssignment_6");
			builder.put(grammarAccess.getSqrtUnaireNumberAccess().getTypeAssignment_0(), "rule__SqrtUnaireNumber__TypeAssignment_0");
			builder.put(grammarAccess.getSqrtUnaireNumberAccess().getVarNameLeftAssignment_1(), "rule__SqrtUnaireNumber__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getSqrtUnaireNumberAccess().getVarNameRightAssignment_4(), "rule__SqrtUnaireNumber__VarNameRightAssignment_4");
			builder.put(grammarAccess.getExpUnaireListAccess().getTypeListLeftAssignment_0(), "rule__ExpUnaireList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getExpUnaireListAccess().getListNameLeftAssignment_1(), "rule__ExpUnaireList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getExpUnaireListAccess().getTypeListRightAssignment_4(), "rule__ExpUnaireList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getExpUnaireListAccess().getListNameRightAssignment_6(), "rule__ExpUnaireList__ListNameRightAssignment_6");
			builder.put(grammarAccess.getExpUnaireNumberAccess().getTypeAssignment_0(), "rule__ExpUnaireNumber__TypeAssignment_0");
			builder.put(grammarAccess.getExpUnaireNumberAccess().getVarNameLeftAssignment_1(), "rule__ExpUnaireNumber__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getExpUnaireNumberAccess().getVarNameRightAssignment_4(), "rule__ExpUnaireNumber__VarNameRightAssignment_4");
			builder.put(grammarAccess.getSumBinaireListValAccess().getTypeListLeftAssignment_0(), "rule__SumBinaireListVal__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getSumBinaireListValAccess().getListNameLeftAssignment_1(), "rule__SumBinaireListVal__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getSumBinaireListValAccess().getTypeListRightAssignment_3(), "rule__SumBinaireListVal__TypeListRightAssignment_3");
			builder.put(grammarAccess.getSumBinaireListValAccess().getListNameRightAssignment_4(), "rule__SumBinaireListVal__ListNameRightAssignment_4");
			builder.put(grammarAccess.getSumBinaireListValAccess().getValNameRightAssignment_6(), "rule__SumBinaireListVal__ValNameRightAssignment_6");
			builder.put(grammarAccess.getSumBinaireListListAccess().getTypeListLeftAssignment_0(), "rule__SumBinaireListList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getSumBinaireListListAccess().getListNameLeftAssignment_1(), "rule__SumBinaireListList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getSumBinaireListListAccess().getTypeListRightAssignment_4(), "rule__SumBinaireListList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getSumBinaireListListAccess().getListNameRightAssignment_9(), "rule__SumBinaireListList__ListNameRightAssignment_9");
			builder.put(grammarAccess.getSumBinaireListListAccess().getListNameRight2Assignment_11(), "rule__SumBinaireListList__ListNameRight2Assignment_11");
			builder.put(grammarAccess.getSumBinaireValValAccess().getTypeVarLeftAssignment_0(), "rule__SumBinaireValVal__TypeVarLeftAssignment_0");
			builder.put(grammarAccess.getSumBinaireValValAccess().getVarNameLeftAssignment_1(), "rule__SumBinaireValVal__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getSumBinaireValValAccess().getVarNameRight1Assignment_3(), "rule__SumBinaireValVal__VarNameRight1Assignment_3");
			builder.put(grammarAccess.getSumBinaireValValAccess().getVarNameRight2Assignment_5(), "rule__SumBinaireValVal__VarNameRight2Assignment_5");
			builder.put(grammarAccess.getProductBinaireListValAccess().getTypeListLeftAssignment_0(), "rule__ProductBinaireListVal__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getProductBinaireListValAccess().getListNameLeftAssignment_1(), "rule__ProductBinaireListVal__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getProductBinaireListValAccess().getTypeListRightAssignment_3(), "rule__ProductBinaireListVal__TypeListRightAssignment_3");
			builder.put(grammarAccess.getProductBinaireListValAccess().getListNameRightAssignment_4(), "rule__ProductBinaireListVal__ListNameRightAssignment_4");
			builder.put(grammarAccess.getProductBinaireListValAccess().getValNameRightAssignment_6(), "rule__ProductBinaireListVal__ValNameRightAssignment_6");
			builder.put(grammarAccess.getProductBinaireListListAccess().getTypeListLeftAssignment_0(), "rule__ProductBinaireListList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getProductBinaireListListAccess().getListNameLeftAssignment_1(), "rule__ProductBinaireListList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getProductBinaireListListAccess().getTypeListRightAssignment_4(), "rule__ProductBinaireListList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getProductBinaireListListAccess().getListNameRightAssignment_9(), "rule__ProductBinaireListList__ListNameRightAssignment_9");
			builder.put(grammarAccess.getProductBinaireListListAccess().getListNameRight2Assignment_11(), "rule__ProductBinaireListList__ListNameRight2Assignment_11");
			builder.put(grammarAccess.getProductBinaireValValAccess().getTypeVarLeftAssignment_0(), "rule__ProductBinaireValVal__TypeVarLeftAssignment_0");
			builder.put(grammarAccess.getProductBinaireValValAccess().getVarNameLeftAssignment_1(), "rule__ProductBinaireValVal__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getProductBinaireValValAccess().getVarNameRight1Assignment_3(), "rule__ProductBinaireValVal__VarNameRight1Assignment_3");
			builder.put(grammarAccess.getProductBinaireValValAccess().getVarNameRight2Assignment_5(), "rule__ProductBinaireValVal__VarNameRight2Assignment_5");
			builder.put(grammarAccess.getDivisionBinaireListValAccess().getTypeListLeftAssignment_0(), "rule__DivisionBinaireListVal__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getDivisionBinaireListValAccess().getListNameLeftAssignment_1(), "rule__DivisionBinaireListVal__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getDivisionBinaireListValAccess().getTypeListRightAssignment_3(), "rule__DivisionBinaireListVal__TypeListRightAssignment_3");
			builder.put(grammarAccess.getDivisionBinaireListValAccess().getListNameRightAssignment_4(), "rule__DivisionBinaireListVal__ListNameRightAssignment_4");
			builder.put(grammarAccess.getDivisionBinaireListValAccess().getValNameRightAssignment_6(), "rule__DivisionBinaireListVal__ValNameRightAssignment_6");
			builder.put(grammarAccess.getDivisionBinaireValListAccess().getTypeListLeftAssignment_0(), "rule__DivisionBinaireValList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getDivisionBinaireValListAccess().getListNameLeftAssignment_1(), "rule__DivisionBinaireValList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getDivisionBinaireValListAccess().getTypeListRightAssignment_3(), "rule__DivisionBinaireValList__TypeListRightAssignment_3");
			builder.put(grammarAccess.getDivisionBinaireValListAccess().getListNameRightAssignment_4(), "rule__DivisionBinaireValList__ListNameRightAssignment_4");
			builder.put(grammarAccess.getDivisionBinaireValListAccess().getValNameRightAssignment_6(), "rule__DivisionBinaireValList__ValNameRightAssignment_6");
			builder.put(grammarAccess.getDivisionBinaireListListAccess().getTypeListLeftAssignment_0(), "rule__DivisionBinaireListList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getDivisionBinaireListListAccess().getListNameLeftAssignment_1(), "rule__DivisionBinaireListList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getDivisionBinaireListListAccess().getTypeListRightAssignment_4(), "rule__DivisionBinaireListList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getDivisionBinaireListListAccess().getListNameRightAssignment_9(), "rule__DivisionBinaireListList__ListNameRightAssignment_9");
			builder.put(grammarAccess.getDivisionBinaireListListAccess().getListNameRight2Assignment_11(), "rule__DivisionBinaireListList__ListNameRight2Assignment_11");
			builder.put(grammarAccess.getDivisionBinaireValValAccess().getTypeVarLeftAssignment_0(), "rule__DivisionBinaireValVal__TypeVarLeftAssignment_0");
			builder.put(grammarAccess.getDivisionBinaireValValAccess().getVarNameLeftAssignment_1(), "rule__DivisionBinaireValVal__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getDivisionBinaireValValAccess().getVarNameRight1Assignment_3(), "rule__DivisionBinaireValVal__VarNameRight1Assignment_3");
			builder.put(grammarAccess.getDivisionBinaireValValAccess().getVarNameRight2Assignment_5(), "rule__DivisionBinaireValVal__VarNameRight2Assignment_5");
			builder.put(grammarAccess.getMinBinaireListValAccess().getTypeListLeftAssignment_0(), "rule__MinBinaireListVal__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getMinBinaireListValAccess().getListNameLeftAssignment_1(), "rule__MinBinaireListVal__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getMinBinaireListValAccess().getTypeListRightAssignment_3(), "rule__MinBinaireListVal__TypeListRightAssignment_3");
			builder.put(grammarAccess.getMinBinaireListValAccess().getListNameRightAssignment_4(), "rule__MinBinaireListVal__ListNameRightAssignment_4");
			builder.put(grammarAccess.getMinBinaireListValAccess().getValNameRightAssignment_6(), "rule__MinBinaireListVal__ValNameRightAssignment_6");
			builder.put(grammarAccess.getMinBinaireListListAccess().getTypeListLeftAssignment_0(), "rule__MinBinaireListList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getMinBinaireListListAccess().getListNameLeftAssignment_1(), "rule__MinBinaireListList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getMinBinaireListListAccess().getTypeListRightAssignment_4(), "rule__MinBinaireListList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getMinBinaireListListAccess().getListNameRightAssignment_9(), "rule__MinBinaireListList__ListNameRightAssignment_9");
			builder.put(grammarAccess.getMinBinaireListListAccess().getListNameRight2Assignment_11(), "rule__MinBinaireListList__ListNameRight2Assignment_11");
			builder.put(grammarAccess.getMinBinaireValValAccess().getTypeVarLeftAssignment_0(), "rule__MinBinaireValVal__TypeVarLeftAssignment_0");
			builder.put(grammarAccess.getMinBinaireValValAccess().getVarNameLeftAssignment_1(), "rule__MinBinaireValVal__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getMinBinaireValValAccess().getVarNameRight1Assignment_4(), "rule__MinBinaireValVal__VarNameRight1Assignment_4");
			builder.put(grammarAccess.getMinBinaireValValAccess().getVarNameRight2Assignment_6(), "rule__MinBinaireValVal__VarNameRight2Assignment_6");
			builder.put(grammarAccess.getMaxBinaireListValAccess().getTypeListLeftAssignment_0(), "rule__MaxBinaireListVal__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getMaxBinaireListValAccess().getListNameLeftAssignment_1(), "rule__MaxBinaireListVal__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getMaxBinaireListValAccess().getTypeListRightAssignment_3(), "rule__MaxBinaireListVal__TypeListRightAssignment_3");
			builder.put(grammarAccess.getMaxBinaireListValAccess().getListNameRightAssignment_4(), "rule__MaxBinaireListVal__ListNameRightAssignment_4");
			builder.put(grammarAccess.getMaxBinaireListValAccess().getValNameRightAssignment_6(), "rule__MaxBinaireListVal__ValNameRightAssignment_6");
			builder.put(grammarAccess.getMaxBinaireListListAccess().getTypeListLeftAssignment_0(), "rule__MaxBinaireListList__TypeListLeftAssignment_0");
			builder.put(grammarAccess.getMaxBinaireListListAccess().getListNameLeftAssignment_1(), "rule__MaxBinaireListList__ListNameLeftAssignment_1");
			builder.put(grammarAccess.getMaxBinaireListListAccess().getTypeListRightAssignment_4(), "rule__MaxBinaireListList__TypeListRightAssignment_4");
			builder.put(grammarAccess.getMaxBinaireListListAccess().getListNameRightAssignment_9(), "rule__MaxBinaireListList__ListNameRightAssignment_9");
			builder.put(grammarAccess.getMaxBinaireListListAccess().getListNameRight2Assignment_11(), "rule__MaxBinaireListList__ListNameRight2Assignment_11");
			builder.put(grammarAccess.getMaxBinaireValValAccess().getTypeVarLeftAssignment_0(), "rule__MaxBinaireValVal__TypeVarLeftAssignment_0");
			builder.put(grammarAccess.getMaxBinaireValValAccess().getVarNameLeftAssignment_1(), "rule__MaxBinaireValVal__VarNameLeftAssignment_1");
			builder.put(grammarAccess.getMaxBinaireValValAccess().getVarNameRight1Assignment_4(), "rule__MaxBinaireValVal__VarNameRight1Assignment_4");
			builder.put(grammarAccess.getMaxBinaireValValAccess().getVarNameRight2Assignment_6(), "rule__MaxBinaireValVal__VarNameRight2Assignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private JavaSFTGrammarAccess grammarAccess;

	@Override
	protected InternalJavaSFTParser createParser() {
		InternalJavaSFTParser result = new InternalJavaSFTParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public JavaSFTGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JavaSFTGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
