drop table Address if exists;
drop table Person if exists;
create table Person (
    id	      integer generated by default as identity (start with 1, increment by 1) not null,
    firstName       varchar(30)      not null,
    lastName    varchar(30)      not null,
    primary key (id)
  );
  
create table Address (
    id	      integer generated by default as identity (start with 1, increment by 1) not null,
    street           varchar(30)      not null,
    city         varchar(30)      not null,
    personId    integer,
    primary key (id)
  );

commit;

