/*
 * generated by Xtext 2.37.0
 */
package projetIDM.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import projetIDM.parser.antlr.internal.InternalJavaSFTParser;
import projetIDM.services.JavaSFTGrammarAccess;

public class JavaSFTParser extends AbstractAntlrParser {

	@Inject
	private JavaSFTGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJavaSFTParser createParser(XtextTokenStream stream) {
		return new InternalJavaSFTParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JavaSFT";
	}

	public JavaSFTGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JavaSFTGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
